### ISSUE TITLE
Question about output

### ISSUE THREAD

**Issue by zxb-caffe** [Xilinx/brevitas#10]
Hello 
The weight has been quantified to INT, but why is the output of each layer still float? Shouldn't it be INT?
I look forward to your reply.

**Comment by volcacius** [comment]
The weights are always represented as floats during training, and they are the product of integer representation by the scale factor. After training, you can access the attributes int_weight and quant_weight_scale on a layer such as QuantConv2d.

**Comment by zxb-caffe** [comment]
In the process of inference. 
Should the weight of each layer be INT? 
Should the output of each layer be INT?
