### ISSUE TITLE
Unsigned quantization of activation function

### ISSUE THREAD

**Issue by mahdi259** [Xilinx/brevitas#1018]
Hi. 

First I appreciate this great project.
I have a question about the quantization type.
Is it possible to define unsigned quantization for activation functions like relu?
For example, the FC model in bnn_pynq uses signed quantization in Quantidentity that isn't sufficient for input features that are unsigned.

Thanks

**Comment by nickfraser** [comment]
Sure, you can do something like this:

```python
from brevitas.nn import QuantReLU
from brevitas.quant import Uint8ActPerTensorFloat

relu = QuantReLU(act_quant=Uint8ActPerTensorFloat)
```

**Comment by mahdi259** [comment]
Thanks a lot. The only thing is that the whole network is quantized to 1, 2 or 4 bits in bnn_pynq examples. Is it possible to define 2 bit unsigned quantization for activation function?

**Comment by nickfraser** [comment]
```python
from brevitas.nn import QuantReLU
from brevitas.quant import Uint8ActPerTensorFloat

relu = QuantReLU(act_quant=Uint8ActPerTensorFloat, bit_width=2)
```

**Comment by mahdi259** [comment]
Thanks

**Comment by mahdi259** [comment]
Hi sorry what does clipping to -1 and 1 mean in the below lines?

https://github.com/Xilinx/brevitas/blob/200456825f3b4b8db414f2b25b64311f82d3991a/src/brevitas_examples/bnn_pynq/models/CNV.py#L85C5-L92C1
