### ISSUE TITLE
Add BNN-PYNQ examples to brevitas_examples

### ISSUE THREAD

**Issue by volcacius** [Xilinx/brevitas#104]
Push Brevitas' version of BNN-PYNQ topologies to brevitas_examples. This would enable simpler FINN-Brevitas tests based on them #84. Conditional to solving #101 first.

**Comment by maltanar** [comment]
Just as a heads-up on this, could you use the variants on this branch:

https://github.com/maltanar/brevitas_cnv_lfc/tree/feature/rework_scaling_clipping

This includes fixes from @ussamazahid96 that increase the accuracy wrt. the previous Brevitas versions of CNV, plus a few other changes from me to make the export work correctly with FINN (narrow range for the weights, specifying device= for the models, removing the objdict config from the checkpoint).

https://github.com/maltanar/brevitas_cnv_lfc/pull/1#issuecomment-598908605

**Comment by volcacius** [comment]
Sure, thanks for the reference.
