### ISSUE TITLE
QuantLinear cannot compute F.Linear beacuse it is flattening the input

### ISSUE THREAD

**Issue by balditommaso** [Xilinx/brevitas#1066]
**Describe the bug**

The new version of Brevitas may have a bug when you apply intger quantization to a dense layer, I have tryed to quantise different models from torchvision and when you reach the last linear layer the multiplication fail.

**Reproducibility**
- [ ] Can be reproduced consistently.
- [ x] Difficult to reproduce.
- [ ] Unable to reproduce.

**Screenshots/Code Example/Log Output**
RuntimeError: mat1 and mat2 shapes cannot be multiplied (131072x1 and 512x1000)

**please complete the following information:**
 - Brevitas version: last
 - PyTorch version: 2.5
 - Operating System / platform: Linux

**Comment by Giuseppe5** [comment]
Thanks for sharing.
Without a script it is difficult for us to reproduce. Does the problem disappear with the previous release of Brevitas?

**Comment by balditommaso** [comment]
Solved, it was my issue
