### ISSUE TITLE
Too much use of GPU Memory when I turn on QuantType.INT

### ISSUE THREAD

**Issue by PASTANERD** [Xilinx/brevitas#107]
![image](https://user-images.githubusercontent.com/37102651/78890435-9f0ce580-7aa0-11ea-8557-9bec825363b9.png)

![image2](https://trello.com/1/cards/5e872d8282fbbe09c91cd84e/attachments/5e8f07f3f823958a6a05f5e7/download?backingUrl=https%3A%2F%2Ftrello-attachments.s3.amazonaws.com%2F5d8ecfe503e0e87c4cf543a3%2F5e872d8282fbbe09c91cd84e%2Ff419c6aee574c4c820efdfdb5425f62c%2Fimage.png)

Hello! First of all, thanks for a wonderful project!
I'm studying the FPGA accelerator for deep learning inference. I'm trying to quantization aware training for my model to use FINN.

When I trained my model without weight_quant_type for QuantConv2d and quant_type for QuantReLU, the model was well trained. However, when I trained it giving those parameters 'QuantType.INT' with a variable 'QUANT_TYPE', training was just shut down and printed some out of memory on GPU like the second picture though I tried to lower the batch size down to 1. 

I wonder why such a huge GPU memory usage occurs when I give QunatType.INT to each QuantConv2d and QuantReLU layers.

the network I trained has 24 QuantConv2d and 20 QuantReLU layers.

**Comment by volcacius** [comment]
Hello,

Quantization-aware training is expensive, there is not way around it unfortuntely. You are trading off extra resources at training time to save resources at inference time. Make sure Pytorch JIT is enabled (it should be by default, but you can set env variable PYTORCH_JIT=1 to be sure). Once the JIT is enabled, moving to latest Pytorch 1.4.0 also helps a bit. If you can't train even at batch 1, you should consider training a smaller model or getting a larger GPU. I wouldn't rule out training on CPU either, if you are working on small images.

Alessandro
