### ISSUE TITLE
Multiple quantized parameters in the same layers

### ISSUE THREAD

**Issue by balditommaso** [Xilinx/brevitas#1122]
I am working with custom layers which have two set of trainable parameters. They follow two different distributions, so it will be useful to have two different quantization scheme for both of them in order to reduce the quantization error. 

Is it already possible in Brevitas? is there ant wolkaround that I can adopt?

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify WeightQuantProxyFromInjector to support two different quantization schemes for two sets of trainable parameters. This change allows custom layers with two sets of parameters following different distributions to be quantized separately, reducing quantization error.

You can review changes in this commit: https://github.com/mnmnk43434/Xilinx-brevitas-1122/commit/ab7d9bf864c65215d475a5a8fa4f05ae37ae5875.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Giuseppe5** [comment]
The answer provided by the bot is wrong (no surprise there).
If you have 2 sets of parameters, I would recommend splitting into two layers with its own custom quantizers. The layers can be very minimal, like:
https://github.com/Xilinx/brevitas/blob/4617f7bd136e96fa21c7f76e3c7e2e37fe563837/src/brevitas/nn/quant_rnn.py#L39-L56


Then you can have your custom layer as:

```python
class NewLayer(torch.nn.Module):
    def __init__(self, weight_quant_1 = Int8WeightPerTensorFloat, weight_quant_2 = Int8WeightPerChannelFloat):
        self.parameter_1= GateWeight(...., weight_quant_1)
        self.parameter_2 = GateWeight(...., weight_quant_1)

    def forward(self, x):
        quant_weight_1 = self.parameter_1.quant_weight() # or self.parameter_1()
        quant_weight_2 = self.parameter_2.quant_weight() # or self.parameter_2()
```

I didn't test this code, take it more as pseudocode but it should give you an idea of where to start

**Comment by balditommaso** [comment]
Great! Thanks for your help!

However, also the bot solution at least looks cool ;)
