### ISSUE TITLE
Drop macOS support

### ISSUE THREAD

**Issue by volcacius** [Xilinx/brevitas#123]
Current macOS support in Github Actions depends on a third party provider, which means that we often get random failures from timeouts that pollutes our CI. We might consider dropping official macOS support.

**Comment by Giuseppe5** [comment]
I'm leaving these two references, don't know if may be useful for our case, but better try before dropping the support.
https://github.community/t5/GitHub-Actions/macOS-builds-timing-out/td-p/37209
https://github.com/actions/toolkit/issues/329

**Comment by volcacius** [comment]
Things seem to have improved lately, closing the issue.
