### ISSUE TITLE
Pytorch 1.5.0 not working

### ISSUE THREAD

**Issue by anadb** [Xilinx/brevitas#125]
Hello I have upgraded PyTorch and Inow  have this error

`Traceback (most recent call last):
  File "train_mnist.py", line 11, in <module>
    import brevitas.nn as qnn
  File "/home/abelanovsky/.local/lib/python3.6/site-packages/brevitas/__init__.py", line 14, in <module>
    torch.ops.load_library(path)
  File "/home/abelanovsky/.local/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/abelanovsky/.local/lib/python3.6/site-packages/brevitas/_C.so: undefined symbol: _ZTIN5torch8autograd4NodeE`

**Comment by Giuseppe5** [comment]
Thanks for the issue. As you can see in #119 and #122 we are actively working on adding support for Pytorch 1.5.0.
 Unfortunately there were some breaking changes that we need to address, so the support is not completely straight forward. 

I'll close the issue as soon as the PR is merged.

**Comment by anadb** [comment]
Ok, sorry I tried to find the same topic but didn't succed.

**Comment by Giuseppe5** [comment]
Support for Pytorch 1.5.0 has been added. MacOS is giving us some troubles not directly related to brevitas. If that is your OS, try using previous versions of pytorch, or let us know and maybe we can find a fix together.
