### ISSUE TITLE
Numerical discrepancies when performing floating point operations between pytorch and FINN

### ISSUE THREAD

**Issue by Tobi-Alonso** [Xilinx/brevitas#143]
The resulting tensors when using pytorch versus onnx are normally close enough but not equal. This probably arises from the order of operations ( FP addition is not associative) and implementations (there methods to limit the error)
This isn't a FINN or Brevitas internal issue but it can affect them. In a large net, chances are that you'll get different activation levels. This was observed in the exported, non streamlined finn-onnx model.

Here is a test code using a simple Conv2d with biporlar weights:

``` python
import onnx  # noqa
import numpy as np
import numpy.random as rnd
import torch
import brevitas.onnx as bo
from finn.core.modelwrapper import ModelWrapper
import finn.core.onnx_exec as oxe
from finn.transformation.infer_shapes import InferShapes

export_onnx_path = "test_act.onnx"

def test_pytorch_vs_onnx_execution():
    in_channels = 256
    out_channels = 1
    kernel_size = 3
    ishape = (1, in_channels,kernel_size,kernel_size) # just one full conv

    # set up conv
    net_torch = torch.nn.Conv2d(in_channels, out_channels, kernel_size, 
        stride=1, padding=0, dilation=1, groups=1, bias=False, padding_mode='zeros')

    rnd.seed(0)
    kernel_np = rnd.rand(out_channels,in_channels,kernel_size,kernel_size).astype(np.float32)
    kernel_np = np.round(kernel_np)*2 -1 # to bipolar weights
    checkpoint = {"weight": torch.tensor(kernel_np).type(torch.FloatTensor)}
    net_torch.load_state_dict(checkpoint)

    #export to onnx
    bo.export_finn_onnx(net_torch, ishape, export_onnx_path)
    model = ModelWrapper(export_onnx_path)
    model = model.transform(InferShapes())

    #run nets
    rnd.seed(23)
    inp_tensor = np.random.uniform(low=0, high=1,size=ishape).astype(np.float32)

    idict = {model.graph.input[0].name: inp_tensor}
    odict = oxe.execute_onnx(model, idict, True)
    produced = odict[model.graph.output[0].name]

    inp_tensor = torch.from_numpy(inp_tensor).float()
    net_torch.eval()
    expected = net_torch.forward(inp_tensor).detach().numpy()

    if not np.isclose(produced, expected, atol=1e-6).all():
        print("prod :", ", ".join(["{:12.10e}".format(x) for x in produced.flatten()]))
        print("expec:", ", ".join(["{:12.10e}".format(x) for x in expected.flatten()]))
        print("diff:", ", ".join(["{:6.4e}".format(x) for x in expected.flatten()-produced.flatten()]))

        #compare to numpy's dot product
        np_result = np.dot(kernel_np.flatten(),inp_tensor.flatten())
        print("numpy dot: {:12.10e} p_diff({:6.4e}) e_diff({:6.4e})".format(np_result,
                    np_result- produced.flatten()[0],np_result-expected.flatten()[0]) )

        return 1

    return 0

if __name__ == '__main__':
    test_pytorch_vs_onnx_execution()
```

**Comment by volcacius** [comment]
ONNX per se does not provide any execution capabilities, it just defines the intermediate representation and the specification of the operators. Here it's FINN executing the ONNX graph, and FINN underneath uses onnxruntime. On top of this, onnxruntime comes with support for different backends.
I would first try to compare pytorch execution vs onnxruntime execution without passing through FINN (see here for example https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html) while playing around with different backends to see how results are possibly shifting. Both Pytorch and onnxruntime come with support for MKL and MKL-DNN, so with proper setup on intel CPU i would be surprised if results were so different, especially for a single layer that maps to a single primitive.

**Comment by volcacius** [comment]
Closing this because of lack of more specific details.
