### ISSUE TITLE
Correct exec of FINN exported CNVs failed on random input

### ISSUE THREAD

**Issue by volcacius** [Xilinx/brevitas#150]
Track failure of the tests reported here https://github.com/Xilinx/brevitas/actions/runs/103974632. 
Execution of exported CNV models (1b1b untrained and 2b2b pretrained) failed to the match the result from Brevitas on randomly generated input. Can't reproduce as the input was generated through numpy without the random seed being set. Best thing is probably to throw Hypothesis at it.

**Comment by maltanar** [comment]
We've seen a couple more export tests randomly fail for CNV export on w1a1 trained:

https://github.com/Xilinx/brevitas/pull/171/checks?check_run_id=765945395
https://github.com/Xilinx/brevitas/pull/171/checks?check_run_id=765945447

This may or may not be related to some random failures for activation exports we are seeing reported in this issue:

https://github.com/Xilinx/brevitas/issues/173

**Comment by volcacius** [comment]
Closing here, move to #173.
