### ISSUE TITLE
quant_weight = int_weight* quant_weight_scale？

### ISSUE THREAD

**Issue by fenling** [Xilinx/brevitas#167]
hi,I have two quenstion to discuss
1、just as the title, did quant_weight = int_weight* quant_weight_scale？
quant_weight, quant_weight_scale, quant_weight_bit_width = self.weight_quant(self.weight)
i print the values like:
![图片](https://user-images.githubusercontent.com/21993862/84366317-3e676980-ac05-11ea-8b2f-d97aed0dc61f.png)
![图片](https://user-images.githubusercontent.com/21993862/84366374-4e7f4900-ac05-11ea-959f-b4b3c7ac8984.png)
but the quant_weight is not equal with  int_weight* quant_weight_scale
eg:15 * 0.0009=0.0135    == 0.00135
-124 * 0.0009=-0.1116   ~= -0.1112
67 * 0.0009=0.0603        ~= 0.0601
-79 * 0.0009=--0.0711    ~=-0.0708
-32 * 0.0009=-0.0288     ~= -0.0287
2、the tensor add a attribute"T" and the T is not same with data.What does t stand for?
![图片](https://user-images.githubusercontent.com/21993862/84367005-378d2680-ac06-11ea-8936-02a6affaa28a.png)

thank you for your attention!

**Comment by Giuseppe5** [comment]
Starting from the second question, T should be the transpose version of your tensor (it is a pytorch related attribute, not brevitas related).

Regarding the first question, you are mostly right. What I mean is that, int_weight * quant_weight_scale gives you the floating point representation of your integer weights; this is different however from _plain_ floating point weights. When converting to integers, you need to take in account the fact that you are not able to express all possible values.
Taking as example the case of signed 8 bit quantization, you are able to represent values from (-128, +127), and then you multiply these values for the scale factor.

What you are trying to do with quantization is finding the best scale factor such that int_weight*quant_weight_scale is as close as possible to floating point weights.

Does it make sense?

**Comment by volcacius** [comment]
1. Yes, quant_weight = int_weight * quant_weight_scale. I wouldn't trust making assumptions based on printing such a limited number of digits of the tensor. You can use torch.set_printoptions(precision=10) to set 10 digits.

**Comment by fenling** [comment]
hi Giuseppe5 ,volcacius:
thank you for your reply.
1、when i use torch.set_printoptions(precision=10) ,the data is right. quant_weight = int_weight * quant_weight_scale.
2、T is the pytorch 1.4.0，has no relation with brevitas.
