### ISSUE TITLE
I cann't find Element-wise add, concat quantization layer

### ISSUE THREAD

**Issue by vdgs** [Xilinx/brevitas#168]
Where are they?

**Comment by volcacius** [comment]
There is no explicit add/concat layer. The point is more general about the fact that you can control scale factors such that you end up having the same scale factors when doing elementwise or adds. When using standard pytorch tensors, you can then use just standard pytorch add and concat. 
When using QuantTensors, add is support when using the + sign, Brevitas will make sure to check that the scale factors of the two tensors added together are the same. For concat, the support is not yet there.
