### ISSUE TITLE
We encountred an exception when trying to retrieve "int_weight" from the model

### ISSUE THREAD

**Issue by solitary-1** [Xilinx/brevitas#172]
We have successfully trained the model of "LFC_1W1A" in bnn_pynq example. When we tried to retrieve "int_weight" from the model, we encountered an exception which stopped us from doing so.

![1456](https://user-images.githubusercontent.com/55728528/84861001-b79e0b00-b0a2-11ea-9aae-def0aa6db840.png)

Here is the code we used to print out "int_weight":
`
    def forward(self, x):
        for mod in self.features:
            if isinstance(mod, QuantLinear):
                print(mod.int_weight())  # where we encountered the exception
`
We want to know if there is a problem with our code or our method of getting the quantized weights. Thanks in advance.

**Comment by volcacius** [comment]
Hello,

What the error is saying is that basically quantization is not enabled. Are you running training using  `brevitas_bnn_pynq_train --network LFC_1W1A --experiments /path/to/experiments` ?

Alessandro

**Comment by solitary-1** [comment]
Follow your steps, but there was an error in running the line of command.Look forward to your reply.
![批注 2020-06-18 112517](https://user-images.githubusercontent.com/55728528/84975079-263ca080-b157-11ea-827a-869acf18389c.jpg)

**Comment by solitary-1** [comment]
> Hello,
> 
> What the error is saying is that basically quantization is not enabled. Are you running training using `brevitas_bnn_pynq_train --network LFC_1W1A --experiments /path/to/experiments` ?
> 
> Alessandro

Follow your steps, but there was an error in running the line of command.Look forward to your reply.
![84975079-263ca080-b157-11ea-827a-869acf18389c](https://user-images.githubusercontent.com/55728528/85034910-2b303d00-b1b5-11ea-9a78-6e4e2934ade0.jpg)

**Comment by volcacius** [comment]
Fixed by #200 .
