### ISSUE TITLE
JIT error after latest merge.

### ISSUE THREAD

**Issue by nickfraser** [Xilinx/brevitas#180]
After the latest merge into `dev`, I'm getting a very, very long QuantAvgPool related, JIT-related error on both PyTorch v1.4.0 and v1.3.1. Full output of error [attached](https://gist.github.com/nickfraser/159b1667802a3c34434a00679f4ef82d).

Reverting back to 67be9b58c1c63d3923cac430ade2552d0db67ba5 fixes the error, using:
```
pip install --upgrade git+https://github.com/Xilinx/brevitas.git@67be9b58c1c63d3923cac430ade2552d0db67ba5
```

Has the interface for QuantAvgPool changed?

**Comment by volcacius** [comment]
I pushed a fix, can you please check if that solves it for you? Thanks

**Comment by nickfraser** [comment]
Yes, this is fixed. Thanks.
