### ISSUE TITLE
tensor_clamp_ste fails when max_val does not have the same shape a 'x' on @dev

### ISSUE THREAD

**Issue by nickfraser** [Xilinx/brevitas#181]
Issue is essentially in the title. Applies to the current dev branch. I'm not sure the specific commit that caused this issue, but reverting back to 67be9b58c1c63d3923cac430ade2552d0db67ba5 fixes the issue.

Traceback is provided [here](https://gist.github.com/nickfraser/e6335d3d43c758359b4e15d4aa6918f0).

**Comment by volcacius** [comment]
It's an error on tensors being on different devices, is this after a load_state_dict or before? The removal of zero_hw_sentinel means we are bit more sensitive to state_dict not being properly restored to the correct device.

**Comment by nickfraser** [comment]
Sorry for the delay, got a chance to look at this again. This is after `load_state_dict`.

**Comment by volcacius** [comment]
Can you try the following, in case it's not like this already:
- instantiate the model, but don't move it to gpu yet
- load_state_dict with map_location='cpu'
- move the model to target gpu

**Comment by nickfraser** [comment]
This workaround works. Not sure if this should close the issue or not as the previous state dict was saved with the correct device locations already.

**Comment by volcacius** [comment]
I'd try re-exporting the state dict in the latest dev branch and see if the above flow is still necessary. If that's the case, I can look into exactly what's the problem.

**Comment by nickfraser** [comment]
I've tested this, unfortunately it still fails in the same way, even when the state dict is exported with the latest branch.

**Comment by volcacius** [comment]
Haven't seen this being reported in a while, reopen if the same issue still shows up.
