### ISSUE TITLE
Installation erroe in virtual environment  of Ubuntu

### ISSUE THREAD

**Issue by manwu1994** [Xilinx/brevitas#185]
Hi, can you help me ? Than you very much.
When I try to install  pip install -e . in virtual environment , the error as follows:
------------------------------------------------------------------------------------------
Installing collected packages: Brevitas
  Running setup.py develop for Brevitas
    ERROR: Command errored out with exit status 1:
     command: /home/py37/py37/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/brevitas/setup.py'"'"'; __file__='"'"'/home/brevitas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/brevitas/
    Complete output (27 lines):
    running develop
    running egg_info
    creating Brevitas.egg-info
    writing Brevitas.egg-info/PKG-INFO
    writing dependency_links to Brevitas.egg-info/dependency_links.txt
    writing entry points to Brevitas.egg-info/entry_points.txt
    writing requirements to Brevitas.egg-info/requires.txt
    writing top-level names to Brevitas.egg-info/top_level.txt
    writing manifest file 'Brevitas.egg-info/SOURCES.txt'
    reading manifest file 'Brevitas.egg-info/SOURCES.txt'
    writing manifest file 'Brevitas.egg-info/SOURCES.txt'
    running build_ext
    building 'brevitas._C' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/home
    creating build/temp.linux-x86_64-3.7/home
    creating build/temp.linux-x86_64-3.7/home/brevitas
    creating build/temp.linux-x86_64-3.7/home/brevitas/brevitas
    creating build/temp.linux-x86_64-3.7/home/brevitas/brevitas/csrc
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/brevitas/brevitas/csrc -I/home/py37/py37/lib/python3.7/site-packages/torch/include -I/home/py37/py37/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/py37/py37/lib/python3.7/site-packages/torch/include/TH -I/home/py37/py37/lib/python3.7/site-packages/torch/include/THC -I/usr/include/python3.7m -I/home/py37/py37/include/python3.7m -c /home/brevitas/brevitas/csrc/ops_register.cpp -o build/temp.linux-x86_64-3.7/home/brevitas/brevitas/csrc/ops_register.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    In file included from /home/brevitas/brevitas/csrc/ops_register.cpp:29:0:
    /home/brevitas/brevitas/csrc/ops_register.hpp:29:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    /home/py37/py37/lib/python3.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.2.0-alpha' to '0.2.0a0'
      normalized_version,
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/py37/py37/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/brevitas/setup.py'"'"'; __file__='"'"'/home/brevitas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by volcacius** [comment]
Hello,

Brevitas received a few major updates recently that might have fixed this, feel free to reopen if you still have problems.

Alessandro
