### ISSUE TITLE
Request to add new layers

### ISSUE THREAD

**Issue by CedricEMSE** [Xilinx/brevitas#186]
I am currently working on an implementation of a UNet architecture. I need different layers to realize this architecture: **ConvTranspose2d** and **Upsample**. Could you add them on brevitas? 

Thank you very much.

**Comment by volcacius** [comment]
Hello,

I'm adding experimental support here #206 , please not they are not supported by any custom export backend (FINN or others) at the moment.
Let me know how it goes.

Alessandro

**Comment by volcacius** [comment]
Landed on master, closing.
