### ISSUE TITLE
Runtimeerror when use attribute BitWidthParameter()

### ISSUE THREAD

**Issue by YouanLi** [Xilinx/brevitas#192]
my code is  as follow,

   weight_bit_width_impl_override=BitWidthParameter(bit_width_init=4, min_overall_bit_width=2,
                                                                                                                    max_overall_bit_width=8,
                                                                                                                    restrict_bit_width_type=RestrictValueType.POWER_OF_TWO,
                                                                                                                    override_pretrained=True))
and the error is
  File "/..../python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
torch.jit.Error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/..../brevitas/brevitas/core/bit_width.py", line 127, in forward
    def forward(self, zero_hw_sentinel: Tensor) -> Tensor:
        if self.max_bit_width is not None:
            raise Exception("Not implemented yet.")
            ~~~~~~~~~~~~~~~~~ <--- HERE
        bit_width = torch.abs(self.bit_width_offset) + self.bit_width_base
        bit_width = self.restrict_bit_width(bit_width)
RuntimeError: Exception

**Comment by YouanLi** [comment]
and when I start to use weight_max_overall_bit_width, it has the same mistake.

**Comment by volcacius** [comment]
Hello,

As the error says clamping bit width from above is not yet implemented. In a recent update I'm not exposing the option anymore so that there is no confusion.

Alessandro
