### ISSUE TITLE
ActQuantProxyFromInjector forward fails when is_quant_enabled is False

### ISSUE THREAD

**Issue by pvrancx** [Xilinx/brevitas#211]
When not using quantization in a quantized activation function the forward method fails with:

>   File runtime_quant.py", line 123, in forward
>     return QuantTensor(*x, signed=self.is_signed)
> TypeError: __new__() got multiple values for argument 'signed'
> 

Steps to reproduce:

create a quantized activation module without quantization implementation, e.g:

`relu = QuantReLU(act_quant=None)
`
or

`relu = QuantReLU(act_quant=DefaultBiasQuantInjector) # fp
`

`relu(torch.randn(10, 3, 32, 32)) # fails
`

The issue seems to be that the fused_activation_quant_proxy in ActQuantProxyFromInjector is replaced with the activation function:

```
 def __init__(self, act_quant_injector: Injector):
         ....
        elif self.is_act_enabled and not self.is_quant_enabled:
            self.fused_activation_quant_proxy = act_impl
```

However act_impl for relu is simply the torch relu which returns a single tensor. Forward expects a tuple:

```
   def forward(self, x: Union[Tensor, QuantTensor]) -> QuantTensor:
            .....
            x = self.fused_activation_quant_proxy(x)
            return QuantTensor(*x, signed=self.is_signed)  # x is now a single tensor, not a tuple
```

**Comment by volcacius** [comment]
Hello,

Thanks for spotting this. I merged a fix into master a couple of days ago, can you check if using the latest commit solves it?

Alessandro

**Comment by pvrancx** [comment]
Fixed on the latest commit. Thanks!
