### ISSUE TITLE
Export LeNet model to ONNX error

### ISSUE THREAD

**Issue by unlimt** [Xilinx/brevitas#221]
Hi,
	I have trained the LeNet example on "Getting started" section and saved the parameters to a checkpoint. 
But there is error when I want to export it to an ONNX file (calling torch.onnx.export). 
Does anyone give me some advice how to fix it ? Thank you very much !

[export_onnx-err.log](https://github.com/Xilinx/brevitas/files/5499412/export_onnx-err.log)

**Comment by volcacius** [comment]
Hello,

Which ONNX backend are you trying to target?

**Comment by unlimt** [comment]
Hi,
    I used CPU for training, then export the model by calling torch.onnx.export(). I think backend = 'CPU' in this case. 
My environment: 
Windows 10 + conda (python 3.6), torch = 1.3.1, torchvision = 0.4.2
Is there any more information you need ? Much thanks for your help.

**Comment by volcacius** [comment]
Hello,

I meant to ask, which ONNX backend library (e.g. onnxruntime) are you planning to use after export? The main supported backends are FINN https://github.com/Xilinx/finn and PyXIR https://github.com/Xilinx/pyxir for FPGA acceleration, while onnxruntime support is still in progress.
