### ISSUE TITLE
Binary activation

### ISSUE THREAD

**Issue by YouanLi** [Xilinx/brevitas#229]
Hi,

Is Brevitas also supporting Binary activation? when I set quant_type to be BINARY, it appeared this error.

Exception: Binary activation supports only signed activations

Best regards,
Youan

**Comment by volcacius** [comment]
Hello,

Yes Brevitas supports binary activation for signed activations, meaning QuantHardTanh or QuantIdentity. If you look into the bnn_pynq example folder you can see how it's used. 

Alessandro

**Comment by YouanLi** [comment]
Thank you very much.
