### ISSUE TITLE
Quantization Does Not Save Storage Space

### ISSUE THREAD

**Issue by yihenghe** [Xilinx/brevitas#230]
Hi,

Thanks for the great package that you guys provide. I have one question about the storage space after quantization-aware training. I tried to replace all layers such as nn.Linear and nn.Conv1d in my model with Brevitas’ layers, and I retrained my model for several epochs. However, after I saved the model after training, the storage space of my model did not change compared to using torch’s nn layers. As I used 8 bits quantization, I originally expected my storage space to be saved by 4x. Could you please help me with this? Thanks!

**Comment by volcacius** [comment]
Hello,

Thanks for checking out Brevitas. In general quantization aware training, including Brevitas, uses floating point values to represent integer values. To save on space/computation you need to export the model to an actual integer based backend. 

The current supported backends are [FINN](https://github.com/Xilinx/finn) and [PyXIR](https://github.com/Xilinx/pyxir/tree/dev) for deployment to Xilinx's FPGAs. 

I'm also working on export to standard ONNX (accelerated through onnxruntime) as well as pytorch's own torch.nn.quantized.functional operators, but I need to finish merging-in support for zero-point first. Keep an eye on this branch for when that happen https://github.com/Xilinx/brevitas/tree/zero_point . Once that's done you will be able to export Conv/Linear layers with 8bit weights and outputs. See for example https://github.com/Xilinx/brevitas/blob/zero_point/test/brevitas/export/test_standard_onnx_export.py for ONNX (I haven't trained anything with that yet so it might be very much broken, but feel free to try it). 

I haven't looked into exporting quantized weights only yet to be honest, it's not a scenario that is commonly supported by backends I'm familiar with, but if you have a custom compiler/backend it's relatively straightforward to extract the integer weights and scale factors from each individual layer, you can just call module.int_weight() and module.quant_weight_scale().

Hope this answer your question.

Alessandro
