### ISSUE TITLE
add Customized Float point format support

### ISSUE THREAD

**Issue by smsskil** [Xilinx/brevitas#234]
At present, Brevitas doesn't support Customized Float point data.  However, there are some papers showing that using Block Float point (BFP) has advantages for quantization-aware training. Also integrated with customized FP (different exponent and mantissa)

**Comment by volcacius** [comment]
Hello,

Integer quantization with per channel scale factor is a form of block floating point. 
Regarding using customized floating-point formats on an individual element basis (say for both forward and backward pass), the way Brevitas is designed is not really friendly to achieve that goal. I'd move the problem to the tensor backend level (like bfloat16 is implemented in Pytorch/XLA). In the long term integration with MLIR through npcomp could achieve those kind of things, but at the moment it's not a priority.

Alessandro
