### ISSUE TITLE
ImportError in brevitas.loss.weighted_bit_width

### ISSUE THREAD

**Issue by dapeter** [Xilinx/brevitas#244]
When trying to import from brevitas.loss.weighted_bit_width, the following error occurs:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    from brevitas.loss.weighted_bit_width import *
  File "\brevitas_install_path\brevitas\loss\weighted_bit_width.py", line 10, in <module>
    from brevitas.utils.quant_utils import *
  File "\brevitas_install_path\brevitas\utils\quant_utils.py", line 41, in <module>
    from brevitas.proxy.parameter_quant import WeightQuantProxy
ImportError: cannot import name 'WeightQuantProxy' from 'brevitas.proxy.parameter_quant'
```

I assume this was caused by the refactoring in 034a99e9a4214c32910cb0d7e0b1357fdd49cbb5 which removed the WeightQuantProxy as well as the ActivationQuantProxy. Still, the imports for both the WeightQuantProxy as well as the ActivationQuantProxy are used in brevitas.utils.quant_utils.

**Comment by volcacius** [comment]
Hello,

That's a good point, thanks for reporting it. Haven't trained a learned bit width network in a while so I totally forgot to update those. I'll push a fix to dev branch.

Alessandro

**Comment by dapeter** [comment]
Hi Alessandro,

thank you very much for fixing it.

Best regards
David

**Comment by volcacius** [comment]
Hello,

I pushed a fix to dev branch as well as a couple basic tests to use as a reference and stop further regressions. Feel free to reopen if there are more problems, and best of luck with your experiments, learned bit width is kind of tricky and the loss functions implemented there are relatively basic.

Alessandro
