### ISSUE TITLE
QuantActMixin does not allow passing Proxy

### ISSUE THREAD

**Issue by pvrancx** [Xilinx/brevitas#245]
`QuantActMixin.__init__ ` throws an error if argument 

`act_quant: Union[ActQuantProxyProtocol, Type[Injector]]`

is an instance of ActQuantProxyProtocol. The problem is the issubclass test that fails if the first argument is not a class.

from brevitas/brevitas/nn/mixin/act.py:

```
        if act_quant is None:
             ...
        elif issubclass(act_quant, Injector):    # throws error if act_quant is not a class
           ....
        else:
            assert isinstance(act_quant, ActQuantProxyProtocol)   #  can never be reached
```

simple fix would be:

`elif isinstance(act_quant, type) and issubclass(act_quant, Injector):
`

**Comment by volcacius** [comment]
Hello,

Thanks for reporting this, I'll push a fix.
On a side note, I'm glad someone that is not me is actually using this sort of more 'advanced' features (even if they are completely undocumented and not very well tested). Please let me know if whatever you are working on makes it into a paper/presentation/whatever public, that kind of feedback from a respected ML shop like yours can help a lot in showing that my work has value beyond the sort of very narrow/benchmark-oriented stuff I currently use it for. 

Alessandro

**Comment by volcacius** [comment]
Fixed in https://github.com/Xilinx/brevitas/commit/8773677a7b33f29945c45bd2906b3ed7089d2803 . It's up on master.
