### ISSUE TITLE
About Injector

### ISSUE THREAD

**Issue by liyue2ppy** [Xilinx/brevitas#247]
I am trying to implement my own ternary quantizer on Brevitas. For achieving it, I am reading the source code of Brevitas now. And I am confused about the Injector part. I can see it is a interface between Conv layer and TernaryQuant, but other than that I know nothing about it. I also find no comment on it. Can you give me a more specific explanation?  Thanks in advance!

**Comment by volcacius** [comment]
Hello,

Thanks for checking out Brevitas. I'm revamping the existing implementation to simplify how to implement new quantizers, there is already experimental support in the dev branch. I'm also adding new documentation to explain how things works together, it should be done in the next few days. Keep an eye on dev branch for new commits to README.

Alessandro

**Comment by liyue2ppy** [comment]
It's exciting news! Thanks!

**Comment by volcacius** [comment]
Find the first draft of the tutorial on quantizers here, using the new simplified implementation. https://github.com/Xilinx/brevitas/blob/master/notebooks/03_anatomy_of_a_quantizer.ipynb
