### ISSUE TITLE
Question: How to extract features of a quantized layer

### ISSUE THREAD

**Issue by MohamedA95** [Xilinx/brevitas#271]
Hello,
First of all thanks for your efforts. I have a VGG16 quantized trained model that I would like to extract some features from like
the number of bits for bias and weight and the number of integer bits of those bits.
I already found `QuantConv2d.quant_bias_bit_width()` and `QuantConv2d.quant_weight_bit_width()` That I can use to extract the total number of bits but I could not find a way to get the number of integer bits.
Also regarding `Multiply, Accumulate & OA` bits I only found `max_acc_bit_width()` that gives the max accumulate bit width. I could not find functions to extract this info. Do such functions exist? or am I looking at the wrong files? I went through different classes but I did not find what I am looking for.

**Comment by volcacius** [comment]
Hello,

The default weight quantizer is `brevitas.quant.Int8WeightPerTensorFloat`, which uses a floating-point scale factor, so there isn't a concept of integer vs fractional bits (see e.g. the docs for tensorflow lite weight quantization https://www.tensorflow.org/lite/performance/quantization_spec it's the same scheme). Same thing for activations and biases. If you want proper fixed point weights you need fixed-point quantizers, they are under brevitas.quant.fixed_point e.g. `Int8WeightPerTensorFixedPoint`. Once you use those, the scale factor is going to be a power-of-two number, so you can extract the number of fractional bits by taking `- torch.log2(QuantConv.quant_weight_scale())`.

Regarding multiply-and-accumulate, what info are you looking for? do you need to compute the max accumulate bit width?

Alessandro

**Comment by MohamedA95** [comment]
Hello Alessandro,
Thanks a lot for your response it helped me a lot. 
Regarding multiply-and-accumulate, I also wanted to extract the total number of bits used and which part is int & float. I guess it would also depend on the quantizer used, right?

**Comment by volcacius** [comment]
Hello,

In general yes. You can do the following:

```python
import torch
from torch.nn import Module
from brevitas.nn import QuantIdentity, QuantConv2d
from brevitas.quant import Int8WeightPerTensorFixedPoint, Int8ActPerTensorFixedPoint, Int8Bias


class ExampleModel(Module):

    def __init__(self):
        super().__init__()
        self.inp_quant = QuantIdentity(
            act_quant=Int8ActPerTensorFixedPoint, return_quant_tensor=True)
        self.conv = QuantConv2d(
            5, 10, (3,3),
            weight_quant=Int8WeightPerTensorFixedPoint,
            bias_quant=Int8Bias)
        self.conv.cache_inference_quant_out = True
        self.conv.cache_inference_quant_bias = True

    def forward(self, x):
        return self.conv(self.inp_quant(x))


model = ExampleModel()
model.eval()  # to trigger caching
model(torch.randn(1, 5, 20, 20))

print(-torch.log2(model.inp_quant.quant_output_scale()))  # 6
print(model.inp_quant.quant_output_bit_width())  # 8
print(-torch.log2(model.conv.quant_weight_scale()))  # 10
print(model.conv.quant_weight_bit_width())  # 8
print(-torch.log2(model.conv.quant_bias_scale()))  # 16
print(model.conv.quant_bias_bit_width())  # 8
print(-torch.log2(model.conv.quant_output_scale()))  # 16
print(model.conv.quant_output_bit_width())  # 24
```

Assuming `Q(m, n)` format notation for fixed point with `range = [-(2^(m-1), 2^(m-1)-(2^(-n))]`, `resolution =  2^-n` and `bit-width = m +n` you have: 
- Input is `Q(2, 6)`
- Weight is `Q(-2, 10)`
- Bias is `Q(-8, 16)`
- Output accumulator is `Q(8, 16)`

A couple of things to note:
- 24 bits for the output accumulator is the very worst case bound, as computed by the `max_acc_bit_width` function. You could do better by say inheriting from QuantConv2d and defining your own `max_acc_bit_width` that takes into account say statistics of the output based on calibration data. 
- There are different options for bias quantization depending on the quantizer. `Int8Bias` means you have that `bias_bit_width()` is set at 8, while `quant_bias_scale()` is the product of `quant_weight_scale()` and` quant_input_scale()`. If you used the `Int8BiasPerTensorFixedPoint` quantizer you would have had that `quant_bias_scale()` was a standalone value, indipendent of input of weight. If you used `IntBiasExternalBitWidth` you would have had bias `Q(8, 16)`, and in turn the output accumulator would have shifted to `Q(9, 16)`.

Let me know if you have more questions.

Alessandro

**Comment by MohamedA95** [comment]
Hello @volcacius, 
Thanks a lot for your fast response. Really appreciate it.
Kindly excuse my late response I had an exam :)
If you allow me I have one last question from what I understood from your comment in  `Q(m,n)`  m and n represent the number of bits, one thing that I did not catch how could this be negative.
Thanks again for your support.

**Comment by volcacius** [comment]
Hello,

m+n is the number of bits. For example for weights m=-2 and n=10 the sum is -2+10=8. It means that all your bits are fractional bits, and on top of that you also have two implicit zeros to the right of the fixed point, with the smallest number you can represent = 2^(-n) = 2^(-10) = 0.0009765625. The semantics are the same as HLS ap_fixed datatype https://www.xilinx.com/html_docs/xilinx2020_2/vitis_doc/use_arbitrary_precision_data_type.html

Alessandro
