### ISSUE TITLE
Unknown error, please help!

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#273]
The error is as follows, how can I fix it？
code:           
 out = qnn.QuantCat((self.branch1(x), self.branch2(x)), dim=1)
error:
 "The quantizer passed does not adhere to the quantization protocol.")
RuntimeError: The quantizer passed does not adhere to the quantization protocol.

**Comment by volcacius** [comment]
Hello,

QuantCat is a Module (as anything under brevitas.nn), you cannot use it as a function. You need:


```python
class Model(nn.Module):
    ....
    self.quant_cat = QuantCat()

def forward(...):
    ....
    out = self.quant_cat((self.branch1(x), self.branch2(x)), dim=1)
    ....
```

**Comment by YZW-explorer** [comment]
> Hello,
> 
> QuantCat is a Module (as anything under brevitas.nn), you cannot use it as a function. You need:
> 
> ```python
> class Model(nn.Module):
>     ....
>     self.quant_cat = QuantCat()
> 
> def forward(...):
>     ....
>     out = self.quant_cat((self.branch1(x), self.branch2(x)), dim=1)
>     ....
> ```

Thank you very much! I have another question to ask whether the function of quant_cat is the same as that of torch.cat, but the object of quant_cat is QuantTensor

**Comment by volcacius** [comment]
If you have two QuantTensor that you want to concatenate you can simply call .cat on it, but they have to have the same scale. For example:

```python
class Model(nn.Module):
    ....
    self.quant_id = QuantIdentity(return_quant_tensor=True)
    
def forward(x):
    out1 = self.quant_id(self.branch1(x))  # out1 is a QuantTensor
    out2 = self.quant_id(self.branch2(x))  # out2 is a QuantTensor
    out = out1.cat((out2,), dim=1)  # out1.scale == out2.scale == out.scale
```

QuantCat is just a shorter way to do the same thing as above, internally it calls a quantizer on all the inputs first so that they have the same scale:

```python
class Model(nn.Module):
    ....
    self.quant_cat = QuantCat()
    
def forward(x):
    out1 = self.branch1(x)  
    out2 = self.branch2(x)  
    out = self.quant_cat((out1, out2), dim=1)  
```

**Comment by YZW-explorer** [comment]
> If you have two QuantTensor that you want to concatenate you can simply call .cat on it, but they have to have the same scale. For example:
> 
> ```python
> class Model(nn.Module):
>     ....
>     self.quant_id = QuantIdentity(return_quant_tensor=True)
>     
> def forward(x):
>     out1 = self.quant_id(self.branch1(x))  # out1 is a QuantTensor
>     out2 = self.quant_id(self.branch2(x))  # out2 is a QuantTensor
>     out = out1.cat((out2,), dim=1)  # out1.scale == out2.scale == out.scale
> ```
> 
> QuantCat is just a shorter way to do the same thing as above, internally it calls a quantizer on all the inputs first so that they have the same scale:
> 
> ```python
> class Model(nn.Module):
>     ....
>     self.quant_cat = QuantCat()
>     
> def forward(x):
>     out1 = self.branch1(x)  
>     out2 = self.branch2(x)  
>     out = self.quant_cat((out1, out2), dim=1)  
> ```

I get it, thank you very much
