### ISSUE TITLE
RuntimeError: Module <class 'brevitas.nn.quant_convtranspose.QuantConvTranspose1d'> not supported for export.

### ISSUE THREAD

**Issue by hdmjdp** [Xilinx/brevitas#280]
RuntimeError: Module <class 'brevitas.nn.quant_convtranspose.QuantConvTranspose1d'> not supported for export.

such as.
By the way, can you tell me how to save melgan model of quant?

**Comment by volcacius** [comment]
Hello,

which target are you trying to export to? There isn't support for quantized conv transpose almost anywhere in inference frameworks unfortunately.

**Comment by hdmjdp** [comment]
@volcacius I want to export to onnx using your standard onnx api.

**Comment by volcacius** [comment]
Unfortunately quantized conv transpose is not supported in the standard onnx opset https://www.github.com/onnx/onnx/tree/master/docs%2FOperators.md so you can't export it there.

**Comment by hdmjdp** [comment]
> Unfortunately quantized conv transpose is not supported in the standard onnx opset https://www.github.com/onnx/onnx/tree/master/docs%2FOperators.md so you can't export it there.


ConvTranspose | 11, 1
-- | --

But this op is surppoerted in opset 11.

**Comment by volcacius** [comment]
Yes that's the floating point op. ONNX has variant for quantized operators. QLinearConv is the quantized variant of Conv and QLinearMatMul is the quantized variant of MatMul. There is no QLinearConvTranspose though.

**Comment by hdmjdp** [comment]
> Yes that's the floating point op. ONNX has variants for quantized operators. QLinearConv is the quantized variant of Conv and QLinearMatMul is the quantized variant of MatMul. There is no QLinearConvTranspose though.

How can I export the quantized model whether using pytorch or onnx?

**Comment by volcacius** [comment]
At the moment you can't unfortunately. In general Brevitas is a research library on quantization, so it supports more experimental stuff at the training level that what is currently supported in downstream inference tools.
