### ISSUE TITLE
Adjusting weight_threshold in Ternay Quant

### ISSUE THREAD

**Issue by uslumt** [Xilinx/brevitas#283]
Hello 
How can I decide the optimal weight_threshold for ternary quantization ?
Passing weight_quant_type as QuantType.TERNARY and setting weight_threshold to some integer worked for few epochs but after some epoch (e.g. 5 or higher ) loss oscillates and most of weights becomes zero.

**Comment by volcacius** [comment]
Hello,

Yeah the current ternary quantization implementation is not great, it's there mostly for retrocompatibility reasons, but I never use it. As a suggestion, go for int quantization with bit_width=2 and narrow_range=True. It ends up being ternary (narrrow range pushes the number of values from 4 to 3) but it trains much more easily.  

Alessandro

**Comment by uslumt** [comment]
Firstly thanks for fast reply, I edited first comment for future reference.
weight_bit_width=2 , narrow_range=True worked.

**Comment by volcacius** [comment]
Make sure that if you are passing narrow_range inline as a keyword argument to say QuantConv2d it needs the weight_ prefix too, so QuantConv2d(..., weight_bit_width=2, weight_narrow_range=True).

Alessandro
