### ISSUE TITLE
How to transfer QuantTensor to Tensor?

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#284]
How to transfer QuantTensor to Tensor?

**Comment by volcacius** [comment]
You can just take QuantTensor.value .

**Comment by YZW-explorer** [comment]
Thank you very much! My next question is how to convert Tensor to QuantTensor

**Comment by volcacius** [comment]
What do you mean with convert? If you want to quantize a tensor use a brevitas.nn.QuantIdentity layer. If you simply want to wrap a tensor in a QuantTensor you can do QuantTensor(tensor), but it won't be quantized.

**Comment by YZW-explorer** [comment]
Thank you so much!
