### ISSUE TITLE
What if I only want to quantify the data and do not want to perform convolution operations on the data? Is there such a layer? For example, this is how this situation is achieved in pytorch.

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#286]
What if I only want to quantify the data and do not want to perform convolution operations on the data? Is there such a layer?
For example, this is how this situation is achieved in pytorch.

code:
import torch
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self, **kwargs):
        super(CenteredLayer, self).__init__(**kwargs)
    def forward(self, x):
        return x - x.mean()

**Comment by volcacius** [comment]
Sorry I'm not sure I understand what you want to do. Are you interested in computing the mean of a quantized tensor?
