### ISSUE TITLE
Is there any brevitas's concatenation function which is equal to torch.cat? and error on some layers are resulting NaN and after moving from training phase to validation phase

### ISSUE THREAD

**Issue by oskarnatan** [Xilinx/brevitas#287]
Hello, currently I am working on my custom model that has several inputs. I want to concatenate several feature maps from multiple inputs on the bottleneck of my model. Each time I train my model, I got this error:

```
dep_f_1_2 = self.conv1_2_dep_f(cat([up_dep_2_1, dvs_f_1_0], dim=1))
  File "/home/oskar/.local/lib/python3.8/site-packages/brevitas/quant_tensor/__init__.py", line 69, in __torch_function__
    return func(*args, **kwargs)
```

My current solution is setting the "return_quant_tensor=False" on the previous layer before the concatenation layer. Then, I use "self.quant_inp(cat([up_dep_2_1, dvs_f_1_0])" to quantize the tensor again before passing it to the next layer. Is there a way to avoid this by giving a function like "brevitas.cat"? Thank you in advance.

note: self.quant_inp = qnn.QuantIdentity(bit_width=3, return_quant_tensor=True)

**Comment by volcacius** [comment]
Hello,

The best way to approach the problem is the following: first you quantize each tensor you want to concatenate with quant_inp (so that they have the same inference scale factor) and then you concatenate them with QuantTensor.cat(list_of_quant_tensor, dim=1). So something like:

```python
from torch import nn
from brevitas import nn as qnn
from brevitas.quant_tensor import QuantTensor

class CatModule(nn.Module):
    def __init__(self):
        super(CatModule, self).__init__()
        self.quant_inp = qnn.QuantIdentity(bit_width=3, return_quant_tensor=True)
     
    def forward(x1, x2):
        qx1 = self.quant_inp(x1)
        qx2 = self.quant_inp(x2)
        return QuantTensor.cat([qx1, qx2], dim=1)
``` 

Let me know if this works.

**Comment by oskarnatan** [comment]
Unfortunately, it still errors

raise RuntimeError("Input scale required")
RuntimeError: Input scale required

what does it mean by "input scale required"?

**Comment by volcacius** [comment]
An "Input scale required" error means that the QuantTensor you are passing to QuantConv2d doesn't have a QuantTensor.scale defined, which is required in some scenarios like bias quantization. How are you defining the convolution?

**Comment by oskarnatan** [comment]
This is one of my convolution block functions on my model.

class convBlock(nn.Module):
    def __init__(self, in_channels, mid_channels, out_channels):
        super().__init__()
        self.relu1 = qnn.QuantReLU(bit_width=3, return_quant_tensor=True) 
        self.conv1 = qnn.QuantConv2d(in_channels, mid_channels, kernel_size=3,
                    stride=1, padding=1, padding_mode='zeros',
                    weight_bit_width=3, bias_quant=BiasQuant, return_quant_tensor=True)
        self.bn1 = qnn.BatchNorm2dToQuantScaleBias(mid_channels,
                    weight_bit_width=3, bias_quant=BiasQuant, return_quant_tensor=True) 
        self.relu2 = qnn.QuantReLU(bit_width=3, return_quant_tensor=True)
        self.conv2 = qnn.QuantConv2d(mid_channels, out_channels, kernel_size=3,
                    stride=1, padding=1, padding_mode='zeros',
                    weight_bit_width=3, bias_quant=BiasQuant, return_quant_tensor=True)
        self.bn2 = qnn.BatchNorm2dToQuantScaleBias(out_channels,
                    weight_bit_width=3, bias_quant=BiasQuant, return_quant_tensor=True) 
    def forward(self, x): #x adalah tensor yang dimasukkan
        x = self.conv1(x) 
        x = self.bn1(x) 
        x = self.relu1(x) 
        x = self.conv2(x) 
        x = self.bn2(x) 
        x = self.relu2(x) 
        return x

Then I modify your CatModule class to retrieve 4 Tensors as follow:

class CatModule(nn.Module):
    def __init__(self):
        super(CatModule, self).__init__()
        self.quant_inp = qnn.QuantIdentity(bit_width=3, return_quant_tensor=True)
    def forward(self, x1, x2, x3, x4):
        qx1 = self.quant_inp(x1)
        qx2 = self.quant_inp(x2)
        qx3 = self.quant_inp(x3)
        qx4 = self.quant_inp(x4)
        return QuantTensor.cat([qx1, qx2, qx3, qx4], dim=1)


The error arises when I fed this convBlock takes an input from the tensor concatenation (from CatModule).
conv_blk = convBlock(in_channels=(4*16), mid_channels=32, out_channels=64)
cat_module = CatModule()
E = conv_blk(cat_module(A, B, C, D))

where A,B,C,D are a tensor with a shape of 16 x 64 x 64 (CxHxW). So, where should I define QuantTensor.scale? Thank you

**Comment by volcacius** [comment]
Hello,

Basically any time you have a layer with bias_quant=Int8Bias (or the IntBiasExternalBitWidth quantizer), the input to that layer has to be a QuantTensor instance with the attribute .scale != None. In your case that means conv1, conv2, bn1, and bn2. 

The simplest solution is to use the Int8BiasPerTensorFloatInternalScaling quantizer, which has its own internal scale factor, so it doesn't need the input to be a QuantTensor with .scale != None. If you don't plan to export the model to some external toolchain it's the best approach.

Otherwise you need to check every input and output and understand where your .scale becomes None.

**Comment by oskarnatan** [comment]
I have changed the bias_quant from 'Int8Bias' to 'Int8BiasPerTensorFloatInternalScaling' as suggested. However, I still got this error:

```
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [122,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "train3q.py", line 1201, in <module>
    main()
  File "train3q.py", line 1047, in main
    train_log, new_params_lw, lgrad = train(batches=train_batches, model=model,
  File "train3q.py", line 306, in train
    score['tot_lidseg_loss'].update(tot_lidseg_loss.item(), 1) #len(config['input'])*len(batch_X[0]))
RuntimeError: CUDA error: device-side assert triggered
```

After checking each layer in my model. I found that some layers are resulting NaN tensors during forward pass:

```
QuantTensor(value=tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         ...,

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]],

.....................

        [[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         ...,

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]]], device='cuda:0',
       dtype=torch.float64, grad_fn=<CatBackward>), scale=None, zero_point=None, bit_width=None, signed=None, training=None)
```

I have made sure that all layers are set bias_quant=Int8BiasPerTensorFloatInternalScaling except qnn.QuantMaxPool2d, qnn.QuantUpsample, and qnn.QuantDropout layer since they don't have 'bias_quant' parameter. I have changed the input tensors to QuantTensors using qnn.QuantIdentity. All layers are set return_quant_tensor=True except final activation layers so that I can perform loss and metric computation as usual.

Thus, I think changing the bias_quant to Int8BiasPerTensorFloatInternalScaling is not the solution. Do you have another recommendation? or could you please tell me how to set QuantTensor with .scale != None? Thank you in advance.

**Comment by oskarnatan** [comment]
Update.

I already know which layers are causing the problem but I still don't know why these layers. I skip these layers and provide dummy Tensors on some outputs (my model has 10 outputs, performing various tasks). Thus, I can train my model.

However, after the training phase is done and go for the validation phase. This error arises:

`
File "/home/oskar/.local/lib/python3.8/site-packages/brevitas/quant_tensor/__init__.py", line 160, in check_scaling_factors_same
    raise RuntimeError("Scaling factors are different")
RuntimeError: Scaling factors are different
`

It says that the scaling factors are different. How come? the model is exactly the same and all I do is just change the setting of the model from model.train() (for training) to model.eval() (for validation). Thank you.

**Comment by volcacius** [comment]
Hello,

Any time you are adding or concatenating together two QuantTensor, they need to have the same scale factor. This is not enforced at training time because there are many scenarios where for a given training batch the training scale factor is != final inference scale factor, but it is enforced at inference time. This is why you get an error with eval() but not with train(). 

To simplify your life, I would do the following: disable bias quantization everywhere (bias_quant=None, which is default), set return_quant_tensor=False everywhere. Remove QuantAvgPoo2d, QuantUpsample, QuantMaxPool, QuantDropout, BatchNorm2dToQuantScaleBias. Keep only linear layers like QuantLinear and QuantConv2d and activations like QuantReLU and QuantIdentity, the rest should be standard torch.nn layers, and focus on getting the accuracy you want. This is going to remove the issue with "scaling factors are different" as well as all the issues with bias.
You won't get a full integer neural network that maps 1:1 to hardware, but it's still 90% close. If you need the remaining 10% you can do additional retraining later on. 
Getting everything perfectly quantized all together at the first attempt is hard, it's hard even for me that I wrote the library. It's always best to have an incremental approach.

**Comment by oskarnatan** [comment]
Hello,

Thank you, I have followed your suggestions, and now it's working. I only quantize the conv2d layer and activation layer (relu and sigmoid).
