### ISSUE TITLE
FINNManager.export error: RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_bilinear2d

### ISSUE THREAD

**Issue by oskarnatan** [Xilinx/brevitas#295]
Hello,

Currently, I am training my custom QNN using Brevitas. Due to some issues in #287 , I decide to only use qnn.QuantConv2d and qnn.QuantRelu, then let the other layers (concat, sigmoid, pool, upsample) originally from torch.

I have also managed my input model to become NxCxHxW with no multiple inputs nor various shape as in #290 
However, after the training and validation phase has done and I am going to save the onnx model using FINNManager.export, this error arises:

```
File "/home/oskar/.local/lib/python3.8/site-packages/brevitas/core/quant/int_base.py", line 129, in forward
    y_int = self.to_int(scale, zero_point, bit_width, x)
  File "/home/oskar/.local/lib/python3.8/site-packages/brevitas/core/quant/int_base.py", line 106, in to_int
    y = x / scale
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Yes, I train my model with my GPU and I am sure that I have done something like this:
```
device = torch.device("cuda:0")
model = model.to(device)
loss_func = loss_func().to(device)
batch_X = batch_X.to(device)
batch_Y_true = batch_Y_true.to(device)
batch_Y_pred = model(batch_X)
loss = loss_func(batch_Y_true, batch_Y_pred)
```

And here is how I save the model:
```
finn_inshape = (1, 25, 100, 100)
FINNManager.export(model, input_shape=finn_inshape, export_path='model_weights_finn.onnx')
```

The training process is working as usual and all tensors are already in cuda:0. So, how can there be 2 devices detected in FINNmanager.export? How to solve this problem? thank you.

**Comment by oskarnatan** [comment]
update:
I found that this error also arises on PytorchQuantManager and StdONNXManager

**Comment by oskarnatan** [comment]
update:

I solve the issue by passing a torch tensor instead of giving input shape. To be more specific I change this:
```
finn_inshape = (1, 25, 100, 100)
FINNManager.export(model, input_shape=finn_inshape, export_path='model_weights_finn.onnx')
```
to this:
```
in_tensor = torch.ones(1, 25, 100, 100, dtype=torch.double, requires_grad=False)
in_tensor = in_tensor.to(device)
FINNManager.export(model, export_path=config['mod_dir']+'/model_weights_finn.onnx', input_t=in_tensor)	
```

However, this error arises:
```
up_fmap_3_0 = self.up(fmap_3_0)
  File "/home/oskar/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/oskar/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/oskar/.local/lib/python3.8/site-packages/brevitas/nn/quant_upsample.py", line 86, in forward
    assert x.scale is not None, 'Input scale factor required to interpolate correctly'
AssertionError: Input scale factor required to interpolate correctly
```

It seems there is some problem on upsampling layer. It says that input scale factor is required. I am sure that I have pass the scale_factor to my 'self.up' here:
`self.up = qnn.QuantUpsample(scale_factor=2, mode='bilinear', align_corners=True, return_quant_tensor=False)`
This one is also doesn't work:
`self.up = qnn.QuantUpsamplingBilinear2d(scale_factor=2, return_quant_tensor=False)`

So, what does it means by "scale factor"? where should I define the scale factor? Thank you in advance

**Comment by oskarnatan** [comment]
Update:

I change all the layers other than qnn.QuantConv2d and qnn.QuantReLU back to torch.nn.
Thus I change the upsampling layer to this:
`self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)`

However, I still got this error on FINNManager.export:
```
FINNManager.export(model, export_path='model_weights_finn.onnx', input_t=in_tensor)
  File "/home/oskar/.local/lib/python3.8/site-packages/brevitas/export/onnx/base.py", line 57, in export
    return cls.export_onnx(module, input_shape, export_path, input_t, **kwargs)
  File "/home/oskar/.local/lib/python3.8/site-packages/brevitas/export/onnx/base.py", line 105, in export_onnx
    torch.onnx.export(module, input_t, export_path, **kwargs)
  File "/home/oskar/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/oskar/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/oskar/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 647, in _export
    proto, export_map = graph._export_onnx(
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_bilinear2d
```

It seems that the export module still has an issue with upsampling layer. Do you have any suggestions for me? I need to export my model to .onnx file so that I can continue to the next step described in https://finn.readthedocs.io/en/latest/end_to_end_flow.html

thank you in advance

**Comment by volcacius** [comment]
Hey, thanks for reporting the issue with device() I'll look into it. As a general note though QuantUpsample is not supported by FINN, you would need to implement it yourself.

**Comment by oskarnatan** [comment]
Ok thanks
