### ISSUE TITLE
Missing variables on the branch of recurrent_rebased

### ISSUE THREAD

**Issue by dongzwhitsz** [Xilinx/brevitas#298]
Hi, I got some problem on the recurrent_rebased code. Some variables like `StatsInputViewShapeImpl`, `SCALING_SCALAR_SHAPE`, `ZERO_HW_SENTINEL_NAME`, `ZERO_HW_SENTINEL_VALUE`, in the code of `quant_lstmlayer.py`, `quant_grulayer.py`, imported from brevitas, are not available in the source code of brevitas. I think they were missed when updated in the codebase of the brach. Would you update the missing part? It can't run successfully  by the `test_lstm.py`, showing error `ImportError: cannot import name 'SCALING_SCALAR_SHAPE'. Thanks.

**Comment by dongzwhitsz** [comment]
The missing part can be found in the `recurrent` branch.

**Comment by volcacius** [comment]
Hi,
Both recurrent and recurent_rebased are WIP branches, I wouldn't use them.
