### ISSUE TITLE
Error running tutorial example __init__() got an unexpected keyword argument 'signed_weight'

### ISSUE THREAD

**Issue by ZackPashkin** [Xilinx/brevitas#304]
Error running tutorial example __init__() got an unexpected keyword argument 'signed_weight'from brevitas.export import PytorchQuantManager
torch 1.8.1
colab
```

pt_lenet = MixedFloatQuantLeNet(bias_quant=False, reduced_act_quant=True, signed_weight=True)

# ... training ...

traced_pt_lenet = PytorchQuantManager.export(pt_lenet, input_shape=(1, 3, 32, 32))
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-4df1aa20026d> in <module>()
      1 from brevitas.export import PytorchQuantManager
      2 
----> 3 pt_lenet = MixedFloatQuantLeNet(bias_quant=False, reduced_act_quant=True, signed_weight=True)
      4 
      5 # ... training ...

TypeError: __init__() got an unexpected keyword argument 'signed_weight'

**Comment by volcacius** [comment]
Hi,

Thanks for spotting the typo, yes it should be weight_signed=True. I'll fix it.
