### ISSUE TITLE
Can brevitas load a pre-trained model before starting quantization-aware training?

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#306]
Can brevitas load a pre-trained model before starting quantization-aware training?

**Comment by volcacius** [comment]
Yes as long as the structure of the model is the same. With the default activation quantizers you are going to get errors related to the fact that there are no keys for the scale factor of the activations. You can set the env variable BREVITAS_IGNORE_MISSING_KEYS=1 to avoid it.

**Comment by YZW-explorer** [comment]
Thank you very much! Are there any relevant examples? Where do I set the env variable BREVITAS_IGNORE_MISSING_KEYS=1

**Comment by YZW-explorer** [comment]
I have used model.load_state_dict() but there is an error of MISSING_KEYS

**Comment by volcacius** [comment]
Setting env variable depends on your own OS + env. For example with bash on linux you do `export BREVITAS_IGNORE_MISSING_KEYS=1` before calling a python script that imports brevitas. Once you do that you won't get the missing key error. Alternatively instead of setting an env variable you can also do the following:

```python
import brevitas
brevitas.config.IGNORE_MISSING_KEYS = True

# rest of your code
```

**Comment by YZW-explorer** [comment]
Thank you very much! But there are still errors

 Missing key(s) in state_dict: "cls_convs.0.conv.weight", "cls_convs.0.bn.weight", "cls_convs.0.bn.bias", "cls_convs.0.bn.running_mean", "cls_convs.0.bn.running_var", "cls_convs.1.conv.weight", "cls_convs.1.bn.weight", "cls_convs.1.bn.bias", "cls_convs.1.bn.running_mean", "cls_convs.1.bn.running_var", "reg_convs.0.conv.weight", "reg_convs.0.bn.weight", "reg_convs.0.bn.bias", "reg_convs.0.bn.running_mean", "reg_convs.0.bn.running_var", "reg_convs.1.conv.weight", "reg_convs.1.bn.weight", "reg_convs.1.bn.bias", "reg_convs.1.bn.running_mean", "reg_convs.1.bn.running_var", "gfl_cls.weight", "gfl_cls.bias", "gfl_reg.weight", "gfl_reg.bias", "scales.0.scale", "distribution_project.project", "backbone.conv1.1.weight", "backbone.conv1.1.bias".

**Comment by volcacius** [comment]
Any error like on things like the weights of a convolution means that you renamed or moved that layer. You need to make sure you replace a torch.nn.Conv2d with a brevitas.nn.QuantConv2d without renaming it or moving it to a different module.

**Comment by YZW-explorer** [comment]
I have observed that some parameters of the bn layer are missing, such as: cls_convs.0.bn.weight", "cls_convs.0.bn.bias", but the bn layer is not used in the model I built with torch.nn, I replaced a torch .nn.Conv2d with a brevitas.nn.QuantConv2d. Why is there an extra bn parameter?

**Comment by volcacius** [comment]
If you are adding a layer (like bn) that wasn't there before you are going to get a 'missing key' error. None of this is specific to Brevitas, it's just how PyTorch works.

**Comment by YZW-explorer** [comment]
Thank you very much! I just use brevitas.nn.QuantConv2d to replace torch.nn.Conv2d and load the pre-trained model, but an error message says that I am missing the parameters of the bn layer, but I did not create the bn layer. Why is this happening?

**Comment by volcacius** [comment]
I would check that you can correctly load the weights before introducing any layer from Brevitas.
