### ISSUE TITLE
pytorch imitate the quantitative forward process of brevitas

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#321]
Dear author, I have used the model built by brevitas to complete QAT training, and the results are very good! This is a very good tool!
Now I want to use the model built by pytorch to imitate the quantitative forward process of brevitas. could you give me a hand?
My model is built by qnn.QuantConv2d and qnn.QuantReLU. I have observed that QuantConv2d has the following variables to obtain scale:
![image](https://user-images.githubusercontent.com/74363764/118746865-9124b900-b88b-11eb-9ce5-dc99c0ccd094.png)
QuantReLUhas the following variables to obtain scale:
![image](https://user-images.githubusercontent.com/74363764/118746922-a699e300-b88b-11eb-83d2-83677353ed79.png)
Can you give me a vivid explanation of the flow of data? Thank you very much!

**Comment by YZW-explorer** [comment]
And QuantMaxPool2d.

**Comment by YZW-explorer** [comment]
Please let me add an explanation: My QuantConv2d has no bias. Through today's observation, I found that the return values of quant_input_scale and quant_output_scale of my QuantConv2d are both None. QuantRelu's quant_input_scale is None, and quant_output_scale and quant_act_scale have return values.

**Comment by YZW-explorer** [comment]
I want to use the scale and parameters trained by brevitas to simulate the process of quantization and dequantization using pytorch. After several days of investigation, I found a method to obtain quantitative weights (int_weight()). But I cannot get the scale of the input value of each convolutional layer. How can I get it? Need your help

**Comment by volcacius** [comment]
Hello,

You can set the attributes cache_inference_quant_inp and cache_inference_quant_out to True on a quantized layer, then set model.eval() and do an inference pass with a input tensor. If you have return_quant_tensor=True enabled on a layer, the output scale of that layer is propagated to the next one and then cached. So the the quant_output_scale/quant_act_scale (they are the same thing) of a quantized activation like QuantReLU becomes the quant_input_scale of the QuantConv2d that comes after it.

**Comment by YZW-explorer** [comment]
Thank you very much! long time no see! Please give me some time. I want to talk with you in detail about the questions in my mind.

**Comment by YZW-explorer** [comment]
Hello author, I have observed the quantization layer Int8ActPerTensorFloat, but I did not set input_quant=Int8ActPerTensorFloat when I created the quantization layer. When I want to quantify the input of the convolutional layer and get the scale of the input value, is it necessary to set it?

**Comment by YZW-explorer** [comment]
Let me add one more question. Is input_scale constant at the end of training? Because I wanted to use the Brevitas post-training parameters to simulate the quantization and de-quantization process on the PyTorch. Thank you very much for your reply.

**Comment by volcacius** [comment]
Yes scales are always constant at the end of training. To quantize the input of a convolution you have two alternative:

```python
class ModelOne(Module):
    def __init__(self):
        super(ModelOne, self).__init__()
        self.quant_inp = qnn.QuantIdentity(bit_width=4, return_quant_tensor=True)
        self.conv = qnn.QuantConv2d(3, 6, 5, weight_bit_width=3)
        
    def forward(self, x):
        out = self.quant_inp(x)
        out = self.conv(out)
        return out

model_one = ModelOne()
model_one.eval()
model_one.conv.cache_inference_quant_inp = True
model_one.conv.cache_inference_quant_out = True
model(torch.randn(2, 3, 10, 10))
model.conv.quant_input_scale() # cached value == to model.quant_inp.quant_output_scale()
model.conv.quant_output_scale() # cached value == to model.conv.quant_input_scale() * model.conv.quant_weight_scale()
```

Or you can do the following:

```python
class ModelTwo(Module):
    def __init__(self):
        super(ModelOne, self).__init__()
        self.conv = qnn.QuantConv2d(3, 6, 5, weight_bit_width=3, input_quant=Int8ActPerTensorFloat)
        
    def forward(self, x):
        out = self.conv(x)
        return out

model_two = ModelTwo()
model_one.eval()
model_one.conv.cache_inference_quant_out = True
model(torch.randn(2, 3, 10, 10))
model.conv.quant_input_scale() # doesn't need caching because input_quant is set within self.conv
model.conv.quant_output_scale() # cached value == to model.conv.quant_input_scale() * model.conv.quant_weight_scale()
```

Note that at the moment only ModelOne works with FINN export, ModelTwo doesn't. Other than that they are the same thing, just different ways to write it.

**Comment by YZW-explorer** [comment]
Thank you very much for your answer! I still have the following questions, sorry to trouble you!
1. Can I get quant_input_scale and quant_output_scale through torch.load after the training, and can they be saved in the PTH file?
2. If I want to use PyTorch to simulate the process of quantization and de-quantization in Brevitas, do you think my following understanding is correct?
2.1
input(float)
2.2
input(int) = input(float)*quant_input_scale()
2.3
weight(int) = int_weight()
2.4
output(int) = nn.conv(input(int),weight(int))
2.5
output(float) = output(int)/quant_output_scale()
