### ISSUE TITLE
pytorch simulates brevitas

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#327]
Thank you very much for your answer! I still have the following questions, sorry to trouble you!
If I want to use PyTorch to simulate the process of quantization and de-quantization in Brevitas, do you think my following understanding is correct?
2.1
input(float)
2.2
input(int) = input(float)*quant_input_scale()
2.3
weight(int) = int_weight()
2.4
output(int) = nn.conv(input(int),weight(int))
2.5
output(float) = output(int)/quant_output_scale()

**Comment by volcacius** [comment]
Yes it's correct.
