### ISSUE TITLE
Questions about input scale

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#328]
Hello, author. I met a new problem when I tried to get the quant_input_scale and quant_output_scale. I'm really sorry to bother you again.
I found that when I set model.train() I couldn't get their values, but when I set model.eval() I could. I have the following two questions:
1. Can I get their values during model training? Or I can only do this with model.eval().
2. If quant_input_scale and quant_output_scale can only be obtained at model.eval(), does the quantization layer quantify the activation value while the model is being trained?

**Comment by volcacius** [comment]
You can get values during training directly from the QuantTensor that goes into the layer and out of the layer, just call the .scale attribute. quant_input_scale and quant_output_scale are just cached values from those tensors.

**Comment by YZW-explorer** [comment]
Thank you very much!

**Comment by YZW-explorer** [comment]
> You can get values during training directly from the QuantTensor that goes into the layer and out of the layer, just call the .scale attribute. quant_input_scale and quant_output_scale are just cached values from those tensors.

Thank you very much for your answers!
