### ISSUE TITLE
Device mismatch in 'QuantConv2d'

### ISSUE THREAD

**Issue by 1y9y9l4** [Xilinx/brevitas#339]
When using export mode, 'QuantConv2d' always output 'cpu' Tensor. This causes an error.
The problem occurs in 'brevitas.export.onnx.finn.function.parameter.QuantizedConvNdPlaceholderFunction'. 

Maybe using **return torch.empty(out_shape, dtype = torch.float, device = x.device)** in _line 55_ of '_brevitas.export.onnx.finn.function.parameter_' will be better.

**Comment by volcacius** [comment]
Thanks for spotting it, I'll push a fix.

**Comment by volcacius** [comment]
Fixed in 0.6.0.
