### ISSUE TITLE
transposed2d convolution scale per channel error

### ISSUE THREAD

**Issue by jmuuu** [Xilinx/brevitas#340]
When I tried to use Quanttranspose2d conv and doubled the input channel,
 an error occurred that the input scale and output scale were different.

I would appreciate it if you could check the error.

**Comment by volcacius** [comment]
Sure, can you please report the exact error you are getting? Thanks

**Comment by jmuuu** [comment]
------------------------------------config----------------------------------------------
WEIGHT_SCALING_IMPL_TYPE = ScalingImplType.STATS WEIGHT_FLOAT_TO_INT_IMPL_TYPE=FloatToIntImplType.ROUND_TO_ZERO 
WEIGHT_SCALING_PER_OUTPUT_CHANNEL = True 
WEIGHT_SCALING_STATS_OP = StatsOp.MAX
 WEIGHT_RESTRICT_SCALING_TYPE = RestrictValueType.POWER_OF_TWO
 WEIGHT_NARROW_RANGE = True


QuantConvTranspose2d(in_channels,
                           out_channels,
                           groups=groups,
                           kernel_size=kernel_size,
                           padding=padding,
                           stride=stride,
                           bias=False,
                           weight_bit_width=bit_width,
                           weight_quant_type=weight_quant_type,
                           weight_scaling_impl_type=weight_scaling_impl_type,
                           weight_scaling_stats_op=weight_scaling_stats_op,
                           weight_scaling_per_output_channel=True,
                           weight_restrict_scaling_type=weight_restrict_scaling_type,
                           weight_narrow_range=weight_narrow_range,
                           weight_float_to_int_impl_type=weight_float_to_int_impl_type,
                           return_quant_tensor=return_quant_tensor,
                                    output_padding=output_padding,
                                    dilation=dilation)

-------------------------------------------------------------------------
-------------------------------layer----------------------------------------
self.enc0 = make_quant_conv2d(3, 8, 3, 2,1 )
  self.enc1 = make_quant_conv2d(8, 16, 3, 2,1)
self.enc2 = make_quant_conv2d(16, 32, 3,2,1 )
self.dec0 = make_quant_trconv2d(32, 16, 3, 2, 1,output_padding=1)
  self.dec1 = make_quant_trconv2d(16, 8, 3, 2,1,output_padding=1)
self.dec2 = make_quant_trconv2d(8, 4, 3, 2, 1,output_padding=1)
self.outputlayer = make_quant_conv2d(32, 3, 3, 1,1,bit_width=16,weight_restrict_scaling_type=RestrictValueType.FP,weight_scaling_per_output_channel=True) self.Hardtanh=make_quant_hard_tanh(bit_width=16,per_channel_broadcastable_shape=(1,3,1,1)) 

--------------error------------------
 x = self.dec0(x)
stats = stats.view(self.stats_output_shape)
RuntimeError: shape '[16, 1, 1, 1]' is invalid for input of size 32


Thanks

**Comment by volcacius** [comment]
I've linked a pull request with a fix, let me know if it solves for you. I need to do a few more tests and then I'll merge it.
