### ISSUE TITLE
Only power-of-two scale factors are supported

### ISSUE THREAD

**Issue by Zhiyuan-Li-ANU** [Xilinx/brevitas#343]
Dear author, I meet a question when I try to use DPUv1Manager.export and DPUv2Manager.export to export onnx file. 
The export file is shown as follow.
`from torch import nn
import torch.nn.functional as F
import brevitas.nn as qnn
from brevitas.quant import Int8WeightPerTensorFixedPoint as WeightQuant
from brevitas.quant import Int8ActPerTensorFixedPoint as ActQuant
from brevitas.quant import Int8BiasPerTensorFixedPointInternalScaling as BiasQuant
from brevitas.export import DPUv1Manager, DPUv2Manager
from brevitas.export import FINNManager
import os
import argparse
import torch
from nanodet.model.arch import build_model
from nanodet.util import Logger, cfg, load_config, load_model_weight

def generate_ouput_names(head_cfg):
    cls_names, dis_names = [], []
    for stride in head_cfg.strides:
        cls_names.append('cls_pred_stride_{}'.format(stride))
        dis_names.append('dis_pred_stride_{}'.format(stride))
    return cls_names + dis_names

def main(config, model_path, output_path, input_shape):
    logger = Logger(-1, config.save_dir, False)
    model = build_model(config.model)   #build config model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage) #build trained model
    load_model_weight(model, checkpoint, logger) #merge 
    #dummy_input = torch.autograd.Variable(torch.randn(1, 3, 416, 416))
    DPUv1Manager.export(model, input_shape, export_path='/home/zhiyuan/nanodet/onnx/dpuv1_lenet.onnx')
    DPUv2Manager.export(model, input_shape, export_path='/home/zhiyuan/nanodet/onnx/dpuv2_lenet.onnx')
    #FINNManager.export(model, input_shape, export_path='/home/zhiyuan/nanodet/onnx/finn_lenet.onnx')
    
if __name__ == '__main__':
    #args = parse_args()
    cfg_path = '/home/zhiyuan/nanodet/config/nanodet-m-416.yml'
    model_path = '/home/zhiyuan/nanodet/workspace/nanodet_m_416_TWO/model_best/model_best.ckpt'
    out_path = '/home/zhiyuan/nanodet/onnx/nanodet_416_QAT.onnx'
    input_shape=(1, 3, 416, 416)
    load_config(cfg, cfg_path)
    main(cfg, model_path, out_path, input_shape)
    print("Model saved to:", out_path)`

And the error message is shown as follow.
**[root][06-06 20:37:26]INFO:Drop parameter cls_convs2.0.structure.0.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs2.0.structure.1.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs2.0.structure.1.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs2.1.structure.0.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs2.1.structure.0.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs2.1.structure.1.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs2.1.structure.1.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.0.structure.0.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.0.structure.0.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.0.structure.1.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.0.structure.1.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.1.structure.0.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.1.structure.0.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.1.structure.1.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter cls_convs3.1.structure.1.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter gfl_cls1.0.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter gfl_cls1.0.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter gfl_cls2.0.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter gfl_cls2.0.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter gfl_cls3.0.input_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
[root][06-06 20:37:26]INFO:Drop parameter gfl_cls3.0.output_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value.
Traceback (most recent call last):

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/export/onnx/base.py", line 97, in export_onnx
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 445, in apply
    module.apply(fn)

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 445, in apply
    module.apply(fn)

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 446, in apply
    fn(self)

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/export/onnx/base.py", line 97, in <lambda>
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/export/onnx/vitis_ai/manager.py", line 27, in set_export_mode
    _set_layer_export_mode(module, enabled)

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/export/base.py", line 100, in _set_layer_export_mode
    m.export_mode = enabled

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/nn/mixin/base.py", line 166, in export_mode
    self.export_handler.prepare_for_export(self)

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/export/onnx/vitis_ai/pyxir/handler.py", line 137, in prepare_for_export
    'input_scale': self.quant_input_scale(module),

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/export/onnx/vitis_ai/handler.py", line 36, in quant_input_scale
    return DPUQuantLayerHandler.neg_scalar_exponent_from_scale(scale)

  File "/home/zhiyuan/anaconda3/lib/python3.7/site-packages/brevitas/export/onnx/vitis_ai/handler.py", line 22, in neg_scalar_exponent_from_scale
    raise RuntimeError("Only power-of-two scale factors are supported")

RuntimeError: Only power-of-two scale factors are supported**

I was very confused since I only replace nn.conv2d into qnn.QuantConv2d, and for the parameters in qnn.QuantConv2d, None of them is called  power-of-two scale factors. How could this happen? I also find some discussion in the issues   that power-of-two scale factors is a parameter used for last version of qnn.QuantConv2d. It quite confused me. 
My part of network is shown as follow. Did I set some parameters wrong? The only difference between my code and your example in Fixed-point quantization for Xilinx DPUs is `return_quant_tensor`. I set it False and you set it True. Whether it is the reason my export process fails.
Here is my network
`class ShuffleV2Block1(nn.Module):  # for stride1
    def __init__(self,
                 inp,
                 oup
                 ):
        super(ShuffleV2Block1, self).__init__()
        branch_features = oup // 2
        self.branch1 = nn.Sequential()
        self.branch2 = nn.Sequential(
            qnn.QuantConv2d(branch_features,branch_features, kernel_size=1, stride=1, padding=0, bias=False,
                            weight_bit_width = 8, weight_quant=SignedWeightQuant, input_quant=ActQuant,
                            output_quant=ActQuant, return_quant_tensor=False),
            nn.BatchNorm2d(branch_features),
            nn.LeakyReLU(),
            qnn.QuantConv2d(branch_features, branch_features, kernel_size=3, stride=1, padding=1, bias=False,
                            groups=branch_features,  weight_bit_width = 8, weight_quant=SignedWeightQuant,
                            input_quant=ActQuant, output_quant=ActQuant, return_quant_tensor=False),
            nn.BatchNorm2d(branch_features),
            qnn.QuantConv2d(branch_features, branch_features, kernel_size=1, stride=1, padding=0, bias=False,
                            weight_bit_width = 8, weight_quant=SignedWeightQuant, input_quant=ActQuant,
                            output_quant=ActQuant, return_quant_tensor=False),
            nn.BatchNorm2d(branch_features),
            nn.LeakyReLU(),
        )

    def forward(self, x):
        x1, x2 = x.chunk(2, dim=1)
        out = torch.cat((x1, self.branch2(x2)), dim=1)
        out = channel_shuffle(out, 2)
        return out`
If I made some mistakes in my code. Could you tell how can I fix it?

**Comment by volcacius** [comment]
Hello,

A few things:
- Batch norm should be fused into the previous conv layers, it's not supported as-is by DPUs.
- Leaky relu is supported by DPUs only as a quantized layer, but it's not supported by Brevitas yet, you should use standard relu.
- Power-of-two scale factors is just a way to say that only fixed point quantizers are supported. I see that you are getting multiple warnings regarding the scale factors being dropped. That is not something that Brevitas does, so it's some issue with the code you are using. I would imagine that the parameter being dropped is what is creating issues.
