### ISSUE TITLE
quantization to INT values

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#356]
Hello,
I would like to use your model as part of a QAT scenario, but I would like to check something first:
I need the quantized values to be of INT type, namely if for example I set the quantization to be of size 8bit, then I would need it to be 2^8 discrete INT values (between -2^4+1 and 2^4 for example), and not 2^8 discrete FP values.
So my question is - does your model quantize into discrete INT values or simply quantizes the values to any type of values?
Thank you!

**Comment by volcacius** [comment]
What you are referring to is the type of scale factor (i.e. the value that maps to integer 1). By default the scale factor can be an arbitrary floating point value. That's what a lot of inference toolchains accelerate and it's good for accuracy.
If you want it to be a power-of-two number, i.e. a fixed point quantization, you can use one of the existing fixed-point quantizer under brevitas.quant.fixed_point example: ```

```python
from brevitas.quant.fixed_point import Int8WeightPerTensorFixedPoint
QuantConv2d(10, 20, 3, weight_quant=Int8WeightPerTensorFixedPoint)
```
Having a scale factor only an integer is probably not a good idea (I don't see it converging easily with standard training hyperparameters), so it's not immediately supported out of the box, but if you really wanna do so you can define your own quantizer like this:

```python
from brevitas.quant.base import IntQuant
from brevitas.quant.solver import WeightQuantSolver

class Int8WeightQuantUnit(IntQuant, WeightQuantSolver):
    scaling_impl_type = 'const'
    bit_width = 8
    narrow_range = False
    scaling_const = 2 ** (8 - 1)
    restrict_scaling_type = 'fp'

m = QuantConv2d(10, 20,3, weight_quant=Int8WeightQuantUnit)
m.quant_weight_scale() # tensor(1.)
```

This make sure that the scale factor is a constant == 1., so your quantized weights are always pure integers.
