### ISSUE TITLE
ensure my values are being quantized

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#357]
Hello,
I am trying to use your toolkit, and as a sanity-check, I tried to look at the quantized layer (in my case, a conv)layer where I quantized solely the weights). The problem is, I can't seem to understand whether or not the quantization occurred - the weights seem to be of FP type. Could you please guide me as to how I can make sure the quantization really occurs, and that I haven't missed anything?
Thank you!

**Comment by volcacius** [comment]
Hi,

You can call quant_conv_layer.int_weight() and see if it returns. If quantization is disabled you will get an error. Example: QuantConv2d(10, 20, quant_weight_type='fp').int_weight() gives you an error.
