### ISSUE TITLE
where is the quantization done?

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#360]
Hello,
could you please refer me to the exact place the quantization is done (the division by scale and adding of zero_point)? For example for the weights of the conv2D layer.
I have been searching your code, and couldn't find it anywhere.
Thank you.

**Comment by volcacius** [comment]
Hello,

This is the default quantization implementation that gets called https://github.com/Xilinx/brevitas/blob/a5bfd6dc5e030f0047ac1ee47932b60e8e873e17/src/brevitas/core/quant/int_base.py#L106 .
