### ISSUE TITLE
default quantization implementation

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#361]
hello,
following issue #360, it appears that even when using the quantized layers, the function [`to_int`](https://github.com/Xilinx/brevitas/blob/a5bfd6dc5e030f0047ac1ee47932b60e8e873e17/src/brevitas/core/quant/int_base.py#L106) isn't called during training. Shouldn't it be called during the forward pass through the quantized layers during training?

**Comment by volcacius** [comment]
Unless you are disabling quantization or using quantizer that is calling into something else (e.g. binary quantization, or your own custom thing), the function you linked is called into by default during training of most quantized layers, e.g. QuantConv2d or QuantIdentity. You can easily verify that with a breakpoint, assuming you don't set BREVITAS_JIT=1 (which would enable torchscript compilation).
