### ISSUE TITLE
the gain of defining the QuantTensor class

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#362]
Hello,
could you please explain the gain in defining the QuantTensor class?
I saw that the fake-quantization is done here: [`fake_quant`](https://github.com/Xilinx/brevitas/blob/master/src/brevitas/proxy/parameter_quant.py#L143), after which the fake-quantized tensor is wrapped in a QuantTensor class. So my question is, if the fake-quantization is already done prior to the instantiation of a QuantTensor class, why not simply pass the fake-quantized tensor (as a tensor)? Why wrap it in a QuantTensor class?

**Comment by volcacius** [comment]
There are various scenarios where you need the propagate the scale or the bit width of the quantized tensor. Bias quantization is one of them (you need to know the scale of the input and the weights). QuantAvgPool, which performs truncation of the input, is another one.
