### ISSUE TITLE
example of quantized network with BN

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#363]
Hello,
could you please upload an example of a network with a quantized BatchNorm?
I saw there was an implementation of a Quantized BatchNorm, but it appears it doesn't inherit from the regular BatchNorm, so I am not quite sure how to use it.
Specifically, I would like to know how to use it in the case where I pass to the quantized conv layers a `return_quant_tensor=True` parameter (I currently tried to use the unquantized version of BN, and kept getting the following error:
```
AttributeError: 'QuantTensor' object has no attribute 'dim'
```

**Comment by volcacius** [comment]
Is there a particular reason why you want to pass a QuantTensor to the batch norm layer?

**Comment by lovodkin93** [comment]
@volcacius 
My current ResNet50 model consists of conv layers, followed by batchNorm layers.
I would've liked to also fake-quantize the biases (in addition to the weights&inputs), which according to the README requires to  pass the QuantTensor.

**Comment by volcacius** [comment]
If you are starting from a pretrained floating point model, the best way to deal with this is to merge the BN layer into the conv layer and go from there. If you wanna have BN during quantization-aware training, leave it unquantized at first and merge it only towards the end.

**Comment by lovodkin93** [comment]
@volcacius According tou what you suggest, this still means that given I want to quantize the biases, I will still encouter the `AttributeError: 'QuantTensor' object has no attribute 'dim'` error during the QAT, unless I don't pass the `return_quant_tensor=True` parameter, which might affect negatively the biases' quantization.

**Comment by volcacius** [comment]
I'm suggesting something different:
1) Train with QuantReLU(return_quant_tensor=False) -> QuantConv2d(return_quant_tensor=False, bias_quant=None) -> BatchNorm2d() or ReLU -> Conv2d -> BatchNorm2d
2)  Merge BatchNorm2d into Conv2d or QuantConv2d
3) Train with QuantReLU(return_quant_tensor=True) -> QuantConv2d(return_quant_tensor=False, bias_quant=Int32Bias)

**Comment by lovodkin93** [comment]
OK, I think I get it now.
Thank you!
