### ISSUE TITLE
define my own quantization function

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#364]
Hello,
I would like to use any of the quantizers that inherit from `WeightQuantProxyFromInjector`, but I would like to change the quantization formula, namely the `impl` in ['impl`'](https://github.com/Xilinx/brevitas/blob/master/src/brevitas/proxy/parameter_quant.py#L143) (or alternatively the `tensor_quant` parameter of the `WeightQuantProxyFromInjector` class). My question is - is there an easy way to do so, without the need to change too much of the code (some sort of method that replaces the `tensor_quant` parameter for example)?
Thank you.

**Comment by volcacius** [comment]
Hi, yes Brevitas is designed for this. You can do the following:

```python
from brevitas.inject import ExtendedInjector

class CustomQuantImpl(nn.Module):
    def __init__(self, my_arg):
         super().__init__()
         self.my_arg = my_arg
   
    def forward(self, weight_tensor_to_quantize):
         # here goes your custom implementation
         return dequant_weight_tensor, scale, zero_point, bit_width
   
class CustomWeightQuant(ExtendedInjector):
    proxy_class = WeightQuantProxyFromInjector
    tensor_quant = CustomQuantImpl
    my_arg = 0.1

m1 = QuantConv2d(weight_quant=CustomQuantImpl) # everything default
m2 = QuantConv2d(weight_quant=CustomQuantImpl, weight_my_arg=0.2) # override default value of my_arg in CustomWeightQuant 
```
