### ISSUE TITLE
Leaky Relu

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#372]
Hey,
I am using a Leaky RelU activation function in my model, and I want to quantize it.
I say that most activations simply inherited from `QuantNLAL` class, and practically all initialized their ancestor (`QuantNLAL`) with the same parameters, with the only difference being the `act_impl` parameter.
So my question is - should the same implementation for the Leaky RelU be suffice? or is there some attribute of `QuantNLAL` that might hinder this approach?

**Comment by volcacius** [comment]
Again though, this one way to do it, not a general one. For example, for a different internal backend leaky relu looks like this: https://github.com/Xilinx/brevitas/blob/c3cfd8dbb9778d3e96ea889dc4ae1c0a8c036771/src/brevitas/graph/target/flexml.py#L58 .
