### ISSUE TITLE
Signed output from quantized activation layer

### ISSUE THREAD

**Issue by DDDDDY1** [Xilinx/brevitas#396]
Hi, I meet this problem when trying to implement a quantized yolov5 model.

The default output from qnn.QuantConv2d is unsigned while it from qnn.QuantIdentity is signed, and during shortcut, I need to use torch.cat to add these two outputs. Then I will get this error:
`Signs are different`

In there a way to set qnn.QuantIdentity output to be unsigned?

Thank you!

**Comment by MohamedA95** [comment]
Hi,
Are you sure that by default the output from `qnn.QuantConv2d` is unsigned? looking at QuantConv2d [definition](https://github.com/Xilinx/brevitas/blob/32cc847fc7cd6ca4c0201fd6b7d185c1103ae088/src/brevitas/nn/quant_conv.py#L168), output quant is disabled by default.

**Comment by DDDDDY1** [comment]
Sorry I integrated bn and activation layer in my conv module, so the unsigned output comes from qnn.QuantReLU instead of qnn.QuantConv2d. How can I set it to be signed?

**Comment by MohamedA95** [comment]
Oh, that is interesting how did you combine them? I am highly interested in fusing Conv & BN, Could you share your code?
Regarding the signed out, I guess it results from the act_quant used in `QuantReLU` by default it's `Uint8ActPerTensorFloat` check [here](https://github.com/Xilinx/brevitas/blob/32cc847fc7cd6ca4c0201fd6b7d185c1103ae088/src/brevitas/nn/quant_activation.py#L54).

**Comment by DDDDDY1** [comment]
Oh I just stacked the three layers to be a QConv module, like this:
```
class QConv(nn.Module):
    # Quantized convolution
    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True, w_bit=4, a_bit=4):
        super().__init__()
        self.conv = qnn.QuantConv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False, weight_bit_width=w_bit, return_quant_tensor=True)
        self.bn = nn.BatchNorm2d(c2)
        # TODO: implement quantized SiLU
        self.act = qnn.QuantReLU(bit_width=a_bit, return_quant_tensor=True) if act is True else (act if isinstance(act, nn.Module) else qnn.QuantIdentity(bit_width=a_bit))

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        x = self.act(x)
        return x
```
Regarding signed out, I set act_quant=Int8ActPerTensorFloat in ReLU, and it works. Thank you so much!

**Comment by MohamedA95** [comment]
Great, Could you close the issue :)

**Comment by g12bftd** [comment]
Hey @DDDDDY1, I would like to fully quantise YOLOv5m using Brevitas, but I'm struggling to do so. Could you please share your code with me?
