### ISSUE TITLE
how to verify the weights are INT8?

### ISSUE THREAD

**Issue by linbaiwpi** [Xilinx/brevitas#4]
hi, I directly replace the Conv2D and Relu in my model with qnn.QuantConv2d and qnn.QuantReLU. However, after training, when I read the weights, it seems still NOT type INT8. Can you help me out of it?

**Comment by volcacius** [comment]
Hi,
You can access the property QuantConv2d.int_weight to extract an integer representation of the weights. The container datatype is going to be int32, as brevitas doesn't assume that you are quantizing to 8 bits or less, but if you quantized to 8 bits or less you can cast it to int8. 
Please be mindful of the fact that you also need take into account the corresponding scale factor, exposed as QuantConv2d.quant_weight_scale . If for example you picked at training time a power-of-two scale factor (passing the argument weight_restrict_scaling_type=RestrictValueType.POWER_OF_TWO to QuantConv2d), then you are going to have a fixed point number.

Alessandro

**Comment by linbaiwpi** [comment]
what I have done is, use the model example in README and train a LeNet5. After training, save the model state_dict in .pth file. After load the saved file, the weight confused me. it looks like
![image](https://user-images.githubusercontent.com/31357378/66718607-b26e1b00-edb3-11e9-97e9-1bbfc16fab2c.png)

I am not familiar with torch. How can I get access to the property "QuantConv2d.int_weight"?

**Comment by linbaiwpi** [comment]
Thank you Alessandro. It works.

**Comment by MinahilRaza** [comment]
Hi, I want to implement 8-bit fixed-point implementation of weights and activations with 7 bits for the fractional part. What value should I pass for weight_restrict_scaling_type?

**Comment by N2606** [comment]
Hi, how can I 
1. extract the actvation scale such as QuantReLU? QuantReLU.quant_act_scale seems not works.
2. extract the bias scale in QuantConv2d?

**Comment by volcacius** [comment]
Please open a separate issue

**Comment by YouanLi** [comment]
hi,
I print out the weight type of int_weight after considering RestrictValueType.POWER_OF_TWO，the weight type is still int32.
