### ISSUE TITLE
Extract the bias scale and activation scale?

### ISSUE THREAD

**Issue by N2606** [Xilinx/brevitas#40]
Hi, thanks for the great work. I have few questions: 
How can I
1. extract the actvation scale such as QuantReLU? QuantReLU.quant_act_scale seems not works.
2. extract the bias scale in QuantConv2d?

**Comment by volcacius** [comment]
Hi,

1) Can you elaborate on what you mean? quant_act_scale was recently turned into a method (I need to do the same for weights), so the issue might be just adding ().
2) Bias scale is the scale of the output, so in QuantConv2d you enable compute_output_scale and return_quant_tensor, bias scale is the scale you get as part of the output QuantTensor.

Alessandro

**Comment by N2606** [comment]
Hi, thanks for reply.
1. yes it solves my problem.
2. Does bias_scale and bias_bit_width always equals to output_scale and output_bit_width? What if I manually set the bias_bit_width in QuantConv2d. In this situation, will the output_bit_width become bias_bit_width  what I set?

**Comment by volcacius** [comment]
Hi, 

1) Great.
2) bias_scale is always equal to output scale in our abstract target hw model. If you want it to be something else, you should define your own custom forward function in QuantConv2d, and pass your own custom scale. If you don't set bias_bit_width, the bit width used for bias quantization is output_bit_width (computed internally based on input and weight). If you set bias_bit_width, then it's bias_bit_width. If bias_bit_width is set, output_bit_width returned by the layer is the largest value between bias_bit_width and the one computed internally.

Alessandro
