### ISSUE TITLE
TRAINED BREVITAS MODEL CAN NOT BE EXPORTED TO ONNX

### ISSUE THREAD

**Issue by aydinkaraa** [Xilinx/brevitas#402]
I have QNN model trained in brevitas. My input shape for a data is (1,3,1024). As I do predictions for my model, I get an accuracy about %80 and on the other hand I am also able to plot a confusion matrix. So; I am sure about my model works. As I want to export this model to onnx in order to use it with FINN I get the error at below.

Please give me any ideas about that.
Sincerely

![image](https://user-images.githubusercontent.com/47895831/173932711-df4e750b-5979-4f39-99fa-2350f14e84a6.png)

**Comment by oskarnatan** [comment]
I have the same issue of 'enable_onnx_checker', how to solve this problem? Thanks in advance
