### ISSUE TITLE
weight_quant_type

### ISSUE THREAD

**Issue by ardeal** [Xilinx/brevitas#406]
Hi,

If I create a layer using the following code which works.
my question is:
key works argument `weight_quant_type` could not be found in the parent class(`QuantLinear, QuantWeightBiasInputOutputLayer, QuantWeightMixin, QuantProxyMixin`). according to Python syntax, it should report error, however, it didn't. I get confused.....
where is `weight_quant_type` defined in those classes?
or is there any other explanation about the syntax of key word argument `weight_quant_type`?

```python
        self.fc1 = qnn.QuantLinear(input_size, 128, bias=True,
                                weight_quant_type=QuantType.INT, 
                                weight_bit_width=8) 
```

**Comment by MohamedA95** [comment]
Doesn't it at least produce a warning that a keyword argument is passed but not used?

**Comment by ardeal** [comment]
@MohamedA95 ,
The code could be run. 
if the `weight_quant_type` syntax is wrong, it should report error instead of warning.

There may be something else that I didn't follow.

**Comment by Giuseppe5** [comment]
The arguments are resolved through dependency injection.

We are planning to refactor how these arguments are handled to make the quantizer interface clearer
