### ISSUE TITLE
Pretrained model in example folder

### ISSUE THREAD

**Issue by andylai0212** [Xilinx/brevitas#42]
Hi, 
Thanks for the great work. I have few questions : 
1. Does the pretrained models in example folder (mobilenet, vgg) fine-tune from floating point model or just train from scratch? And I am wonder how much would it takes for fine-tuning/training? If there is a example training codes would be appreciated.

**Comment by volcacius** [comment]
Hello,

MobileNet V1 and ProxylessNAS finetune from a floating point model. The source is here: https://github.com/osmr/imgclsmob/tree/master/pytorch . I have plans to merge a set of training scripts in the future. In general retraining times depends a lot the precision, the specific topology, and how the floating point model was trained. If you want to see an example, here is the open source submission I did for the MicroNet challange at NeurIPS 2019 https://github.com/volcacius/micronet_competition 

Alessandro
