### ISSUE TITLE
bit_width=4 is not in class definition

### ISSUE THREAD

**Issue by ardeal** [Xilinx/brevitas#424]
Hi,

For the following code, we defined qnn.QuantIdentity with input parameter bit_width=4, but in there is not bit_width in QuantIdentity class.

My questions are:
how will the bit_width=4 passed to quantization function?
where does the quantization happen in the Brevitas code?

```python
self.quant_inp = qnn.QuantIdentity(bit_width=4, return_quant_tensor=True)
```

```python

class QuantIdentity(QuantNLAL):

    def __init__(
            self,
            act_quant: Optional[ActQuantType] = Int8ActPerTensorFloat,
            return_quant_tensor: bool = False,
            **kwargs):
        QuantNLAL.__init__(
            self,
            input_quant=None,
            act_impl=None,
            passthrough_act=True,
            act_quant=act_quant,
            return_quant_tensor=return_quant_tensor,
            **kwargs)



```

**Comment by Giuseppe5** [comment]
The bit_width argument is resolved and passed to the quantizer class through dependency injection.

The quantization happens through proxies who are responsible for calling the quantizers. 
For JIT optimization reasons, in the case of activations, the proxy is also responsible to call the activation implementation (`act_impl`), e.g. torch.nn.ReLU in the case of QuantReLU.



[This ](https://github.com/Xilinx/brevitas/blob/9bb26bf2798de210a267d1e4aed4c20087e0e8a5/src/brevitas/nn/quant_layer.py#LL141C20-L141C29) is where the input is passed to the proxy that will apply first the `act_impl` function and then will call the quantizer's forward
