### ISSUE TITLE
how input tensor is quantized by qnn.QuantiIdentity

### ISSUE THREAD

**Issue by ardeal** [Xilinx/brevitas#437]
Hi,
Please refer to the following code.
I run the following code, and got to know that:
`scale` in `out` is: `0.0391`.
`zero_point` in `out` is `0`

value in `out` is: [1.0156, 1.9922, 3.0078, 3.9844, 4.9609]

my questions are:
1) according the formula in the paper,  `r = s(q-z)`, how to calculate the out value?
2) how is `scale` calculated? is there any code or formula to calculate `scale`?

```python
    quant_inp = qnn.QuantIdentity(bit_width=8, return_quant_tensor=True)
    inp = torch.as_tensor([1,2,3,4,5])
    out = quant_inp(inp)
```

I did the following experiment in python:

![image](https://user-images.githubusercontent.com/6227348/197708218-5249e84f-69c5-4881-b441-68e8eee949c1.png)

in the upper experiment, all the values are exactly equal with corresponding values in `out` except one value:
the quantization resule of the max value in `inp`.

**Comment by Giuseppe5** [comment]
The reason for this behavior is that, with 8bit signed quantization, the floating point values are mapped to the integer range [-128, 127], that has 256 values, including 0. 

To test this, if you were to add -5 to your input, you would notice that that value is quantized as you would expect. 

Similarly, if you define your QuantIdentity with the extra parameter narrow_range=True, the quantization would be in the integer range [-127, 127], and then you would see that both -5 and 5 (in your example) are quantized "correctly".

**Comment by Giuseppe5** [comment]
1. In this particular case, for signed quantization, with a single tensor as input, it is correct (up to some technical details). You must consider that when multiple tensor are passed as inputs, the scale will be adjusted as consequence (in training mode). In evaluation mode, the scale then gets fixed.
2. I am not sure what you mean by _always_
3. The default quantization strategy is [Int8ActPerTensorFloat](https://github.com/Xilinx/brevitas/blob/32cc847fc7cd6ca4c0201fd6b7d185c1103ae088/src/brevitas/quant/scaled_int.py#L191), which use the [IntQuant](https://github.com/Xilinx/brevitas/blob/32cc847fc7cd6ca4c0201fd6b7d185c1103ae088/src/brevitas/quant/base.py#L121) strategy, with the following [zero_point_impl](https://github.com/Xilinx/brevitas/blob/32cc847fc7cd6ca4c0201fd6b7d185c1103ae088/src/brevitas/core/zero_point.py#L63)

I would recommend looking at the the following [tutorial](https://github.com/Xilinx/brevitas/blob/32cc847fc7cd6ca4c0201fd6b7d185c1103ae088/notebooks/Brevitas_TVMCon2021.ipynb) if you haven't already!

**Comment by ardeal** [comment]
@Giuseppe5 
Thank you!

your question: `I am not sure what you mean by always`

in my experiment(in the picture in this first post), if I change the max value of input, the `q = int(round(max/scale))` is always 128 which is 127 if I input my data to ``qnn.QuantIdentity(bit_width=8, return_quant_tensor=True).

**Comment by ardeal** [comment]
Hi @Giuseppe5 
Thank you!

for the following code, the values in `out` is:
`[26.,   51., -128.,  102.,  127.]`

my question is:
how the class `QuantIdentity` quantize them to -128 and 127? what is the formula or logic?

In my following code/my understanding, I always quantize the max value of input to 128 which is not equal with the 127 by `QuantIdentity`
```python
    beta = 5
    scale = (beta*2)/(2**8)
    x = 5
    qf1 = int(round(x/scale))
```


```python
    quant_inp = qnn.QuantIdentity(bit_width=8, return_quant_tensor=True)
    inp = torch.as_tensor([1,2,-5,4,5])
    out = quant_inp(inp)
```

**Comment by Giuseppe5** [comment]
The logic is that with 8 bit you have 256 values at your disposal for quantization. You cannot go from -128 to +128, which would be 257 values (including the zero), thus only from -128 to 127.

When you try to quantize _ - beta_ everything works as you expected. When you try to quantize _beta_ the integer value is clamped back to +127 because +128 is out of range.

If you want to investigate more in details how this happens, I suggest to use a debugger and go through a forward pass of brevitas line by line, and I am sure everything will be very clear immediately.
