### ISSUE TITLE
How to quantize two Floating-Point Tensors to have the same Scale value?

### ISSUE THREAD

**Issue by Coke-das-JHL** [Xilinx/brevitas#439]
I want to add two quantized Tensors.

How to quantize two Floating-Point Tensors to have the same Scale value?

The same QuantIdentity Layer was used, but the quantized Tensors had different Scale values.

Can you tell me the Solution?

![image](https://user-images.githubusercontent.com/68185836/198013156-2459d86d-f427-41b7-ad2b-a75f9d02d15f.png)

**Comment by Giuseppe5** [comment]
Check the section
_How is the activation scale determined by default?_

in the following [tutorial](https://github.com/Xilinx/brevitas/blob/master/notebooks/Brevitas_TVMCon2021.ipynb)

**Comment by Coke-das-JHL** [comment]
I solved it. thank you
