### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by Yumingyuan** [Xilinx/brevitas#46]
C:\Users\86188\brevitas>pip install -e .
Obtaining file:///C:/Users/86188/brevitas
Requirement already satisfied: torch>=1.1.0 in d:\programdata\anaconda346\lib\site-packages (from Brevitas==0.2.0a0) (1.3.0)
Requirement already satisfied: docrep in d:\programdata\anaconda346\lib\site-packages (from Brevitas==0.2.0a0) (0.2.7)
Requirement already satisfied: scipy in d:\programdata\anaconda346\lib\site-packages (from Brevitas==0.2.0a0) (1.0.0)
Requirement already satisfied: packaging in d:\programdata\anaconda346\lib\site-packages (from Brevitas==0.2.0a0) (16.8)
Requirement already satisfied: numpy in d:\programdata\anaconda346\lib\site-packages (from torch>=1.1.0->Brevitas==0.2.0a0) (1.14.0)
Requirement already satisfied: six in d:\programdata\anaconda346\lib\site-packages (from docrep->Brevitas==0.2.0a0) (1.11.0)
Requirement already satisfied: pyparsing in d:\programdata\anaconda346\lib\site-packages (from packaging->Brevitas==0.2.0a0) (2.2.0)
Installing collected packages: Brevitas
  Running setup.py develop for Brevitas
    ERROR: Command errored out with exit status 1:
     command: 'd:\programdata\anaconda346\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\86188\\brevitas\\setup.py'"'"'; __file__='"'"'C:\\Users\\86188\\brevitas\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\86188\brevitas\
    Complete output (18 lines):
    信息: 用提供的模式无法找到文件。
    running develop
    running egg_info
    writing Brevitas.egg-info\PKG-INFO
    writing dependency_links to Brevitas.egg-info\dependency_links.txt
    writing requirements to Brevitas.egg-info\requires.txt
    writing top-level names to Brevitas.egg-info\top_level.txt
    reading manifest file 'Brevitas.egg-info\SOURCES.txt'
    writing manifest file 'Brevitas.egg-info\SOURCES.txt'
    running build_ext
    building 'brevitas._C' extension
    d:\programdata\anaconda346

**Comment by volcacius** [comment]
Sorry but I have a hard time understanding the error message in chinese. As a workaround, try downgrading to pytorch 1.2.0.
