### ISSUE TITLE
Can LSTM  be quantified?

### ISSUE THREAD

**Issue by zuowanbushiwo** [Xilinx/brevitas#475]
Hi  all
     There are LSTM operators in my network，I haven't found the QuantLSTM layer in the master，How to deal with this situation？
Thanks!

**Comment by volcacius** [comment]
Hello,

There is support for QuantLSTM in the dev branch. See an example invocation here https://github.com/Xilinx/brevitas/blob/89d90282a74894e23242f4307e6eaa28f4e52761/tests/brevitas/nn/test_recurrent.py#L182 note that support for export to ONNX is still limited.
