### ISSUE TITLE
EqualizeGraph bug

### ISSUE THREAD

**Issue by Giuseppe5** [Xilinx/brevitas#477]
I believe EqualizeGraph should be considered as a separate, optional step when doing PTQ.

For some models, it just fails because of mismatched dimensions.
In other cases, it does not fail even though it should not work.

For example, in the following case (taken from GoogleNet):
```python
branch1 = self.branch1(x)
branch2 = self.branch2(x)

outputs = [branch1, branch2]
```

Graph Equalization is applied between branch 1 and branch 2, even though the output of the first is not the input of the second layer.

**Comment by volcacius** [comment]
Are the values added together? If so they should be equalized.

**Comment by Giuseppe5** [comment]
The tensor `outputs` then is used as input for another convolution, so I believe Graph Equalization is not correct in that case?

**Comment by volcacius** [comment]
then no yeah

**Comment by Giuseppe5** [comment]
It turns out this was not the case, so closing this.
