### ISSUE TITLE
Problem with QuantConvTransposed2D

### ISSUE THREAD

**Issue by Coke-das-JHL** [Xilinx/brevitas#485]
![image](https://user-images.githubusercontent.com/68185836/208053894-5f7ec3ae-7fbd-4b2c-b4c1-5a8255446e4c.png)
![image](https://user-images.githubusercontent.com/68185836/208054015-9859c70b-5b4e-4379-aefc-6c17630bdfc6.png)

I have a  qusetion about QuantConvTransposed2D . 

I am doing a simple test about quantization. but I got an error. Can you help me? 

Thank you .

**Comment by Giuseppe5** [comment]
Hi!
What Pytorch version are you using?

**Comment by Coke-das-JHL** [comment]
> Hi! What Pytorch version are you using?

torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 

Thank you.

**Comment by Coke-das-JHL** [comment]
> Hi! What Pytorch version are you using?

I am using Pytorch version 1.13.0+cu116. 

Thank you!

**Comment by Giuseppe5** [comment]
Pytorch 1.13 is supported in the dev branch for the moment, and will be supported in main starting from the next release.
If you can use Pytorch 1.10, everything should work fine, otherwise if you really need pytorch 1.13, please install brevitas from the dev branch.

**Comment by Coke-das-JHL** [comment]
> Pytorch 1.13 is supported in the dev branch for the moment, and will be supported in main starting from the next release. If you can use Pytorch 1.10, everything should work fine, otherwise if you really need pytorch 1.13, please install brevitas from the dev branch.

Thank you!
