### ISSUE TITLE
Batchnorm Folding & Bitwidth 

### ISSUE THREAD

**Issue by Coke-das-JHL** [Xilinx/brevitas#494]
Hi, I am doing some experiments using brevitas. 

I'm using BatchNorm folding to create a network with only ReLU and Convolutions. However, A little problem arose.

From 32 bits to 8 bits, performance is good even if BatchNorm Folding is performed. 

However, in the case of 4 bits, performance deteriorates rapidly when BatchNorm Folding is performed.
(The performance before folding is excellent.) 

Can anyone advise on this?

**Comment by Giuseppe5** [comment]
Hi,
Thanks for getting in touch!

Could you give more details on the Quantization process you're using?
Is it QAT? How long are you training for? Are you fine tuning from FP32 or training from scratch?

**Comment by Giuseppe5** [comment]
Closing this issue, but feel free to re-open if you still need help with this!
