### ISSUE TITLE
Can Brevitas fix scale to specific value during training?

### ISSUE THREAD

**Issue by YingXiangLi10** [Xilinx/brevitas#502]
Hi, I have a model which contains a lots of layer, and I want some of the layers' input scale being set to specific value during training.
It seems that we can set scaling_min_val to force the scale bigger than the limit, Can we just force the scale to specific value? 

Thank you for your time.

**Comment by MohamedA95** [comment]
HI,
You can probably create a custom quantizer that sets `scaling_impl_type = ScalingImplType.CONST` like [this](https://github.com/Xilinx/brevitas/blob/aa04fb4bf528932512b57b6b4b46511b491a965b/src/brevitas/quant/ternary.py#L12) which inherts from [here](https://github.com/Xilinx/brevitas/blob/aa04fb4bf528932512b57b6b4b46511b491a965b/src/brevitas/quant/base.py#L223).

**Comment by YingXiangLi10** [comment]
Thanks for your help!!! That's exactly what I need.
