### ISSUE TITLE
Looking for guidance to replicate MobileNet-v1 quantized model

### ISSUE THREAD

**Issue by verderog** [Xilinx/brevitas#517]
I'm trying to replicate the pre-trained quantized version of MobileNet-v1 and am looking for some guidance into what I doing wrong or may be fundamentally misunderstanding. I've created a simple Python script (below) to perform a one-shot inference to compare the output of the floating-point model (https://github.com/osmr/imgclsmob/blob/master/pytorch/pytorchcv/models/mobilenet.py), pre-trained quantized model (https://github.com/Xilinx/brevitas/blob/master/src/brevitas_examples/imagenet_classification/models/mobilenetv1.py), and untrained quantized model retrained with the floating point.  It does this inference for the first image from the ImageNet validation dataset:

```
#!/usr/bin/env python3

from pytorchcv.model_provider import get_model as ptcv_get_model
import torch
from brevitas_examples.imagenet_classification import models
from brevitas import config
import torchvision.transforms.functional as TF

from PIL import Image

config.IGNORE_MISSING_KEYS = True

test_file = "/srv/nfs/imagenet-data/imagenet/ILSVRC2012_val_00000001.JPEG"

def tf_pre_process(img):
    img = TF.resize(img,(224,224))
    img = TF.to_tensor(img) # NOTE: this converts from [0,255] range to [0,1]
    img = TF.normalize(img,mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225])
    return img

def main():
    # instantiate the floating point model, including pre-trained weights and activations
    net_float = ptcv_get_model("mobilenet_w1", pretrained=True) # https://github.com/osmr/imgclsmob/blob/master/pytorch/pytorchcv/models/mobilenet.py

    # instantiate the quantized model, with pre-training.
    net_quant = models.quant_mobilenet_v1_4b(pretrained=True) # https://github.com/Xilinx/brevitas/blob/master/src/brevitas_examples/imagenet_classification/models/mobilenetv1.py

    # instantiate the quantized model, with no pre-training.  Want to propagate the pre-trained floating point weights and activations    
    net_quant_retrained = models.quant_mobilenet_v1_4b(pretrained=False)
    net_quant_retrained.load_state_dict(net_float.state_dict()) # 'retrain' the untrained, quantized model with the floating-point dictionary (https://xilinx.github.io/brevitas/tutorials/tvmcon2021.html#Retraining-from-floating-point)

    net_float.eval()
    net_quant.eval()
    net_quant_retrained.eval()
    
    img = Image.open(test_file)
    img_tensor = tf_pre_process(img).unsqueeze(0) # add batch parameter back in (3x224x224 -> 1x3x224x224)
    
    # perform the inference
    with torch.no_grad():
        out_float = torch.nn.functional.softmax(net_float(img_tensor),dim=1)
        out_quant = torch.nn.functional.softmax(net_quant(img_tensor),dim=1)
        out_quant_retrained = torch.nn.functional.softmax(net_quant_retrained(img_tensor),dim=1)

    # get top-5 results
    top5_float = torch.topk(out_float,5).indices
    top5_quant = torch.topk(out_quant,5).indices
    top5_quant_retrained = torch.topk(out_quant_retrained,5).indices
    
    print("top5_float: " + str(top5_float))
    print("top5_quant: " + str(top5_quant))
    print("top5_quant_retrained: " + str(top5_quant_retrained))

if __name__ == "__main__":
    print("Perform a one-shot inference to compare floating point vs Brevitas quantized pre-trained vs Brevitas quantized re-trained")
    main()
```

I get the following output from this:

```
Perform a one-shot inference to compare floating point vs Brevitas quantized pre-trained vs Brevitas quantized re-trained
top5_float: tensor([[65, 62, 58, 54, 57]])
top5_quant: tensor([[65, 34, 54, 62, 58]])
top5_quant_retrained: tensor([[793, 419, 601,  88, 974]])
```

The top-5 for the floating point model and pre-trained quantized make sense and are relatively close in their predictions.  If I run the full 50000 ImageNet validation set, I see the floating-point give me a top-1 accuracy of 70.4% vs 68.4% with the pre-trained quantized version.  That makes sense to me and they are fairly close.

I'd expect that the top-5 of the re-trained quantized model to give me a similar result to the floating-point and pre-trained quantized models but the predictions are completely different.  I was under the impression that retraining the quantized model (https://xilinx.github.io/brevitas/tutorials/tvmcon2021.html#Retraining-from-floating-point) from the floating-point model would essentially give me the same results as the pre-trained quantized model.  Obviously, that isn't the case.

Searching through old issues, I see this comment in issue #243 from @volcacius:

> Brevitas doesn't do any form of advanced direct quantization, meaning the initialization of quantization is relatively simple. So at the beginning of training it usually looks like it lost all accuracy. 

It seems to me that even though you can load in the floating-point state and get the initial quantizations from that, further training is required to complete the pre-training.  I was hoping I could simply "load things and go". :)

Questions:

- To what extent would I need to re-train the quantized MobileNet-v1 model after loading in the floating-point values?  I don't have to re-train the entire ImageNet training set would I?
- Are there any tutorials or examples for what specifically was done to get MobileNet-v1 quantized?
- Issue #42 references training scripts.  Are any of these scripts available?

Thanks!

FYI, @giop98

**Comment by verderog** [comment]
For what it's worth, I ran the ImageNet validation set against the re-trained quantized model and got 0.09% accuracy across the 50000 images.  So, the comment regarding "looks like it lost all accuracy" holds.

**Comment by Giuseppe5** [comment]
Hello @verderog,
Thanks for the extremely detailed issue!

As you correctly pointed out, just loading the FP weights in a module with quantized modules (weights and activations) is not enough, and further steps are required. At this point you can either try:
- Quantization Aware Training, that will be very helpful especially when you want to quantize your network with low bit-width ( I would say less than 8 bit), which is how the quant_mobilenet weights were obtained, but as you said, it consists in re-training on the entire ImageNet training set; 
- Post-Training Quantization, which is a much faster process that involves a quicker re-adjustment of scale factors and weights, with a fraction of the images (in the order of hundreds or few thousands). 

We are actively improving our support for PTQ, and in the last release we improved and cleaned up the interface to perform calibration and bias correction, and currently there is an open PR to improve weight equalization, as well as other projects and ideas that we hope to push soon out, to get as close as we can to "load things and go".

Regarding tutorial and training scripts, I leave it to @volcacius, but I would like to ask what kind of tutorials were you looking for? 
Are you interested in how to assemble a quantize model starting from its FP counterpart? Or how to perform the training once your model is setup? Or something else entirely?
We are in the process of extending and improving our documentation and tutorials, so it would be nice to know what are the aspects we should focus on.

Please feel free to reach out if you have more questions or if I missed something.

**Comment by verderog** [comment]
@Giuseppe5 

Thank you for the response!  I'm interested in the PTQ aspect.  

I'm coming to Brevitas after having looked at FINN.  For me, a tutorial or guide that shows how to take a pre-trained floating point PyTorch model (specifically, MobileNet-v1) all the way from Brevitas to FINN would be very helpful.

Here are things as I currently understand them for Brevitas.  There are probably gaps so feel free to correct me:

1. Begin with a fully trained floating-point model.
2. Replace the torch layers with their quantized alternatives for weights and activations.  
3. Set up your bit-widths with typical recommendations or guidance on trade-offs (e.g. 8-bit widths for input / 1st layer, etc.)
4. "Re-train" the quantized model, pulling in initial weights and biases from the floating-point model.
5. Perform PTQ.  Or, perform QAT across the entire training set.
6. Export the quantized model to ONNX.

Right now, I'm not sure of the step 5 approach above that was used to get the pre-trained quantized version of MobileNet-v1.  Was it QAT?  Was it PTQ?  

If it was QAT, I assume that would be a huge impediment to the development process.  You define your weight / activation bit widths, then retrain the whole thing across your entire data set.  If you find out you were too narrow and get poor accuracy, you need to loosen things up and then do another full training session.  I'm sure this works, but it seems like it would slow, especially for huge datasets.

If it was PTQ, what are the steps performed for this?  I see this approach is mentioned  at  https://xilinx.github.io/brevitas/tutorials/tvmcon2021.html#Calibration-based-post-training-quantization, so I'll dig into that a bit.

Ultimately, I have a model that is somewhat similar to MobileNet.  I know if I could fully understand how MobileNet was quantized by Brevitas and deployed with FINN, I'd be able to do it with my own custom model.  The only thing I'm balking at is having to re-train it across the full dataset.  I think PTQ would save the day.

Thanks again.

**Comment by verderog** [comment]
@Giuseppe5 

I attempted to use PTQ following the guidance at https://xilinx.github.io/brevitas/tutorials/tvmcon2021.html#Calibration-based-post-training-quantization.  After running calibration, my accuracy went from 0.09% to 0.31%.  Not much of an improvement unfortunately, so I must be doing something incorrectly.

Here is the relevant portions from the calibration script I wrote:

```
net_float = ptcv_get_model("mobilenet_w1", pretrained=True)
net_quant_retrained = models.quant_mobilenet_v1_4b(pretrained=False)
net_quant_retrained.load_state_dict(net_float.state_dict())
net_quant_retrained = calibrate(net_quant_retrained, test_dataloader)
val_acc = validate(net_quant_retrained, val_dataloader)
print("Test accuracy = %f" % (val_acc))
```

The `calibrate` method is nearly identical to the one in the tvmcon2021 link.  The `validate` method simply produces the accuracy metric.  I've verified that the `validate` method is correct for the pre-trained floating point model and the pre-defined quantized model when `pretrained=True`.  As a first pass for PTQ, I calibrated using test_dataloader which loads in the ImageNet test data set (100000 images).  My val_dataloader loads in the ImageNet validation data set (50000 images).

Any ideas what I am doing wrong?

Further, is it possible to accelerate calibration using a CUDA-based host?  I tried transferring the model and batches to my CUDA device, but ran into a tensor mismatch problem (torch.FloatTensor vs torch.cuda.FloatTensor), so I'm wondering if the `calibration_mode` method in Brevitas might be preventing that from working.

Thanks!

**Comment by Giuseppe5** [comment]
Thanks for providing your feedback about PTQ.

The five steps you mention are generally correct. This instance of quantized mobilenet has been trained with QAT, which as you suggested could be a time consuming process.

I was playing with some configurations with PTQ with MobileNet and noticed as well some inconsistencies that I want to investigate further. Also, thanks for letting me know about the CUDA issue, I will add it to my list and come back to you as soon as I know more. 

Unfortunately I am not sure when I will be able to look into these matters and how long it may take to fix everything, but if you spot something that needs to be fixed, please feel free to open a PR!

Thanks for your understanding.

**Comment by verderog** [comment]
I need to revise a couple of numbers above since I interpreted them in error.  I re-ran the validation scoring against loading the quantized MobileNet-v1 model with the floating-point model dictionary and again after loading it with the floating-point dictionary + calibration:

- floating-point re-training only, validation accuracy: 0.11%
- floating-point re-training + calibration, validation accuracy: 30.3%

So, definitely an improvement, but not as much as I had hoped for.  Compare that with 5 epochs of QAT where I see accuracy getting up to 66%.  No matter how you cut it, however, you need to devote a good chunk of time re-training things.

**Comment by verderog** [comment]
I have one additional observation: If I calibrate the quantized model and then save the checkpoint via `torch.save()`, and then attempt to load that saved checkpoint via `torch.load()`, I encounter the following error:

```
]
Traceback (most recent call last):
  File "./train-mobilenet-quant.py", line 260, in <module>
    main()
  File "./train-mobilenet-quant.py", line 169, in main
    net_quant_retrained.load_state_dict(torch.load(args.load_ckpt))
  File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MobileNet:
        Unexpected key(s) in state_dict: "features.init_block.conv.bias", "features.stage1.unit1.dw_conv.conv.bias", "features.stage1.unit1.pw_conv.conv.bias", "features.stage2.unit1.dw_conv.conv.bias", "features.stage2.unit1.pw_conv.conv.bias", "features.stage2.unit2.dw_conv.conv.bias", "features.stage2.unit2.pw_conv.conv.bias", "features.stage3.unit1.dw_conv.conv.bias", "features.stage3.unit1.pw_conv.conv.bias", "features.stage3.unit2.dw_conv.conv.bias", "features.stage3.unit2.pw_conv.conv.bias", "features.stage4.unit1.dw_conv.conv.bias", "features.stage4.unit1.pw_conv.conv.bias", "features.stage4.unit2.dw_conv.conv.bias", "features.stage4.unit2.pw_conv.conv.bias", "features.stage4.unit3.dw_conv.conv.bias", "features.stage4.unit3.pw_conv.conv.bias", "features.stage4.unit4.dw_conv.conv.bias", "features.stage4.unit4.pw_conv.conv.bias", "features.stage4.unit5.dw_conv.conv.bias", "features.stage4.unit5.pw_conv.conv.bias", "features.stage4.unit6.dw_conv.conv.bias", "features.stage4.unit6.pw_conv.conv.bias", "features.stage5.unit1.dw_conv.conv.bias", "features.stage5.unit1.pw_conv.conv.bias", "features.stage5.unit2.dw_conv.conv.bias", "features.stage5.unit2.pw_conv.conv.bias".

```

I assumed that I could re-train the quantized model, calibrate it, and later reload the saved model checkpoint.  It appears that the bias correction stage of model calibration is causing issues.

@Giuseppe5 FYI.

**Comment by verderog** [comment]
@Giuseppe5 

Thanks for the quick response!  I have not done any tweaking to the model, so no, I have not tried changing bit width settings.

**Comment by Giuseppe5** [comment]
I just opened one PR (#522) with one fix to use more effectively our quantized models with PTQ.
Changing manually the bit width of the configuration to 8, I get ~70% accuracy.

The other PR I am planning to do is a notebook with a tutorial on how to do PTQ, but it might take some time.
Let me know your experience after this first changes.

**Comment by verderog** [comment]
I haven't pulled your PR, but manually doubling the "BIT_WIDTH" setting in the configuration and running it against 16000 training images gave me an accuracy of 48.9%.  

My biggest concern with simply increasing the BIT_WIDTH is that I'd like to bring this model into FINN and deploy it to a ZCU104 dev board.  I suspect doubling this parameter would make the synthesized version exceed the amount of resources the board has.  Does that sound accurate?

**Comment by verderog** [comment]
There seems to be a regression using the PR (#522) and/or the "dev" branch.  If I run my test script using my default 0.8.0 install (via `pip install brevitas`), I consistently get an accuracy of ~48% after calibration using BIT_WIDTH set to 8 for the config.  With Brevitas source installed locally (again, "dev" branch) and pulling in your PR, I'm back to 0.1% accuracy.  My test script is identical in both cases.  Only difference is that I set/unset PYTHONPATH to grab the default install or the source w/your PR.

I've re-ran my test a few times, alternating between the default and local clone, and the accuracy follows (default: ~48%, clone + PR: 0.1%).  I don't think it's on my end.

**Comment by Giuseppe5** [comment]
Is your calibration script the same you shared at the top?

**Comment by verderog** [comment]
I don't have a public repo hosting my script, so please see attached.  [train-mobilenet-quant.zip](https://github.com/Xilinx/brevitas/files/10578905/train-mobilenet-quant.zip)

There are two things to be aware of with this:

1) This script assumes you have the Hugging Face imagenet-1k dataset installed (https://huggingface.co/datasets/imagenet-1k).  I have the dataset cached at `/data/huggingface/datasets` on my local machine so you'll likely need to change that line in the `main()` method.  

2) I copied the `quant_mobilenet_v1_4b.ini` to the script location, renamed it `local_quant_mobilenet_v1_4b.ini`, and updated the BIT_WIDTH to 8.  So, the script will need the call to `model_with_cfg` updated with the ini file you are using.

Invocation using the default 0.8.0 Brevitas install:

    ./train-mobilenet-quant.py --load-float-parms --calibrate --test-split 0.0125

Result: Validation accuracy = 0.486620

Invocation using the cloned Brevitas + PR repo:

    PYTHONPATH=<path-to-brevitas-repo>/src ./train-mobilenet-quant.py --load-float-parms --calibrate --test-split 0.0125

Result: Validation accuracy = 0.001000

Explanation of options:

`--load-float-parms` : Load the floating point MobileNet-v1 model and re-train the quantized model weights / activations with them
`--test-split` : Perform the calibration with 1.25% of the training dataset (0.0125 * 1280000 = 16000 images)
`--calibrate` : perform calibration + bias correction with training data subset, then validate the result with the validation dataset.

Note that when the quantized model is loaded, I am *not* pulling in the pretrained version.

Hope this helps!

**Comment by Giuseppe5** [comment]
Hello,

Once the #522 and #523 PRs are merged, I believe all the issues related to PTQ of MobileNet should be resolved.

Regarding the CUDA issue, you need to modify the calibrate function to move your data to your cuda device.
Assuming the model has already been moved to cuda, the calibration function will look like this:

```python
def calibrate(model, data_loader, device):

    with torch.no_grad():
        with calibration_mode(model):
            for _,data in enumerate(tqdm(data_loader)):
                images = data["image"]
                images = images.to(device, non_blocking=True)
                model(images)

        with bias_correction_mode(model):
            for _,data in enumerate(tqdm(data_loader)):
                images = data["image"]
                images = images.to(device, non_blocking=True)
                model(images)        

    return model
```

**Comment by verderog** [comment]
I'm not sure what I was doing wrong initially with the CUDA config, but I've confirmed that is working as expected.

I ran BIT_WIDTH=8 for my calibration config against a merge of those two PRs and get an accuracy of 72.6% for a dataset size of 16000 images.  As an extra data point, bumping up the data set to 64000 images yields about the same accuracy for calibration.

While I don't believe a BIT_WIDTH setting of 8 is going to allow me to fit things on my ZCU104, I do appreciate the updates and fixes.  Thanks!

**Comment by Giuseppe5** [comment]
Both the PRs related to this issue have been merged into dev, so I am closing this.

I am actively working on adding new PTQs techniques to Brevitas, and I will soon try to put together a tutorial about how to use and combine them.
In the meantime, if you need more help or have other issues, feel free to reach out to us.

All the best,
Giuseppe
