### ISSUE TITLE
Scale is not being learned

### ISSUE THREAD

**Issue by ppccww0201** [Xilinx/brevitas#557]
Hello! Thank you for your library that helps quantization experiment for my nework!

I made my network into binarized network. So I made a new Quantizer like:
 ```python
class MyBinaryQuantizer(ExtendedInjector):
    tensor_quant = BinaryQuant
    scaling_impl=ParameterScaling
    scaling_init=1.
    signed = True

class MySignedBinaryActQuantizer(MyBinaryQuantizer):
    proxy_class = ActQuantProxyFromInjector


class MySignedBinaryWeightQuantizer(MyBinaryQuantizer):
    proxy_class = WeightQuantProxyFromInjector
``` 

and I configured my network like:
 ```python
self.identity = qnn.QuantIdentity(act_quant=MySignedBinaryActQuantizer, return_quant_tensor=True)
self.conv1d = qnn.QuantConv1d(in_channels, out_channels, 1, bias=False, weight_quant=MySignedBinaryWeightQuantizer,
                                     return_quant_tensor=True)
if not self.test:
    self.norm = nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01)
else:
    self.norm = qnn.BatchNorm1dToQuantScaleBias(out_channels, eps=1e-3, momentum=0.01,
                                     weight_quant=MySignedBinaryWeightQuantizer,
                                     weight_bit_width=8,
                                     bias_quant=MySignedBinaryWeightQuantizer,
                                     bias_bit_width=8,
                                     return_quant_tensor=True)
self.act = nn.ReLU()
``` 

Here is the issue. When I checked the output of conv1d layer, the scale value was always 1!
I hoped that only the initial scale value is 1, and I wanted it to be learned.
But it is always 1.

What is the problem? Thank you!

**Comment by MohamedA95** [comment]
Hi,
Are you sure you are checking the correct values? `conv1.quant_weight_scale()` or `conv1.quant_output_scale()`?

**Comment by ppccww0201** [comment]
Hi, thank you for your reply!

Actually, I checked the scale of QunatTensor which is made by `self.conv1d` layer.

So like you said, I tried to check the  `self.conv1d.quant_weight_scale()` and `self.conv1d.quant_output_scale()`.
Here is the forward code and result.

```python
    def forward(self, inputs):
        quant_inputs = self.identity(inputs)
        quant_inputs = quant_inputs.permute(0,2,1)
        x = self.conv1d(quant_inputs)
        print(self.conv1d.quant_weight_scale().item(), self.conv1d.quant_output_scale())
        x = x.permute(0,2,1)
        torch.backends.cudnn.enabled = False
        if not self.test:
            x = torch.squeeze(self.norm(x.permute(0, 2, 1))).permute(0, 2, 1) if self.use_norm else x
        else:
            x = torch.squeeze(self.norm(x.permute(2, 1, 0))).permute(2, 1, 0) if self.use_norm else x
        torch.backends.cudnn.enabled = True
        xr = self.act(x)
        x_max = torch.max(xr, dim=1, keepdim=True)[0]

        if self.last_vfe:
            return x_max
        else:
            x_repeat = x_max.repeat(1, inputs.shape[1], 1)
            x_concatenated = torch.cat([x, x_repeat], dim=2)
            return x_concatenated
``` 
![image](https://user-images.githubusercontent.com/91767741/226243838-a99ba3a4-a512-4ddc-bd39-20074ed7fe8b.png)

I inserted "print" into forward code to check the scale of weights and outputs of conv1d layer.
`self.conv1d.quant_weight_scale()` is always 1.0, and `self.conv1d.quant_output_scale()` is always None.
I think something is wrong about None value of `self.conv1d.quant_output_scale()`, and unlearnable scale.

Can you find the problem of my network or Quantizer? Thank you

**Comment by MohamedA95** [comment]
I do not know what could be wrong here, your implementation is similar to the one in the third notebook.

**Comment by Giuseppe5** [comment]
Closing this, but if you are still facing this or any other issue let us know.

**Comment by surajpandey353** [comment]
Hi @Giuseppe5,

I have a exactly opposite problem, if we could fix the scale_factors manually and avoid gradient being propagated to it.
"""
self.quant_weight_scale.requires_grad = False
AttributeError: 'method' object has no attribute 'requires_grad'
"""
Thanks!
