### ISSUE TITLE
Quantized activation functions

### ISSUE THREAD

**Issue by g12bftd** [Xilinx/brevitas#619]
Are there any plans to add more quantized activation functions (eg QuantGeLu, QuantSoftmax, QuantHardTanH)? Or can these be somehow implemented at the moment?

**Comment by Giuseppe5** [comment]
Hello,

A baseline implementation of any of the activation functions you mentioned would be to add a QuantIdentity module after the float activation itself, assuming that the HW that will run the quantized model supports the possibility of having certain ops in floating point and you want to ensure that the output of the activation is quantized.

If you are looking for more sophisticated implementations, then the implementation becomes backened-dependant.

Please let me know if this answers your question!

**Comment by g12bftd** [comment]
Hey @Giuseppe5, sounds good! Thanks :)
