### ISSUE TITLE
How to implement QuantIdentity Layer?

### ISSUE THREAD

**Issue by Coke-das-JHL** [Xilinx/brevitas#632]
I am currently trying to extract Test Vectors to implement HW based on a deep learning model implemented with Brevitas. 

In hardware, all the data flow will be at Integer Level, so I was hoping to get some tips on how I can implement a Quantidentity Layer that gives Integer outputs for Integer inputs. 

However, I am not sure how to implement QuantIdentity Layer as HW, can you help me?

**Comment by Giuseppe5** [comment]
Hello,

Unfortunately I am not sure if I could help, as this is highly dependent on the characteristics of the HW you are using and in general something not directly related to Brevitas but more on the kind of operations/optimizations that your HW permits
