### ISSUE TITLE
How do I create "quant_melgan_8b_generator-8fe7e01f.pth" file

### ISSUE THREAD

**Issue by dzungcamlang** [Xilinx/brevitas#72]
Hi @Giuseppe5 and @volcacius 

I tried text_to_speech with your PR  on [colab](https://colab.research.google.com/drive/1heB9_tieKREL2lAyDW7YUT8x-y8zD6Ct), but I can't find the way to create quant 8bit in origin pretrained of [repo](https://github.com/seungwonpark/melgan). Can you help me?
Thanks so much.

**Comment by Giuseppe5** [comment]
I tried to open your colab link but I think I don't have permissions.
Anyway, I don't undestand what you mean with PR? My PR was merged in the master branch few weeks ago now.
If you clone this repository and stay on the master branch (after installing it), you can execute the validation script of melgan, and the pth file will be downloaded automatically.

Alternatively, you can find the file at this [link](https://github.com/Xilinx/brevitas/releases/download/quant_melgan_8b-r0/quant_melgan_8b_generator-8fe7e01f.pth), but then you should modify the script to load it by hand.

If you need any more help, check out the [examples readme](https://github.com/Xilinx/brevitas/blob/master/examples/text_to_speech/README.md), or let me know.

**Comment by dzungcamlang** [comment]
Hi, @Giuseppe5 ,
Thanks your answer, I want clear my question like this, where is the code you make file "quant_melgan_8b_generator-8fe7e01f.pth",, can you share with me and other people has want make it on yourself.
Thanks you,
btw, I make colab on public.

**Comment by Giuseppe5** [comment]
Oh sorry if I miss-understood your question. 
Unfortunately the training scripts to generate the checkpoint files are not yet released and there are no plans to release them for the immediate future.
If many people will be interested in them, we may re-consider the idea.

**Comment by dzungcamlang** [comment]
Thanks you so much @Giuseppe5.

**Comment by hdmjdp** [comment]
@Giuseppe5 why not release training script?
