### ISSUE TITLE
How QuantHardTanh works

### ISSUE THREAD

**Issue by wanglu4042** [Xilinx/brevitas#746]
Hi, I have a question for QuantHardTanh.
I set it like the picture downbelow.
![image](https://github.com/Xilinx/brevitas/assets/132076700/16e07f38-5384-424e-beb6-56346717b711)

but after I saved the module as onnx, I found  that QuantHardTanh was changed like this.
![image](https://github.com/Xilinx/brevitas/assets/132076700/d38be5e8-406e-4582-a04e-fd92a5cc7c22)

And in FINN, it was like this:
![image](https://github.com/Xilinx/brevitas/assets/132076700/f9d0017b-4e90-429c-9507-6861cd6030bb)

And all parameters were set to float32, especially the part called MultiThreshold, it had the parameters like this:
![image](https://github.com/Xilinx/brevitas/assets/132076700/62fe74a5-f06b-4d09-a725-7edc817029a3)

Could you please tell me, how are these numbers calculated when they are INT8 and also in float32?
Thanks!!
Looking forward to your reply!

**Comment by Giuseppe5** [comment]
Hi, 

Generally speaking, it is always useful to have a minimal script to reproduce your observations, including versions of the packages involved.

Many thanks!
