### ISSUE TITLE
Fix QCDQDecoupledWeightQuantProxyHandlerMixin return args

### ISSUE THREAD

**Issue by Giuseppe5** [Xilinx/brevitas#747]
https://github.com/Xilinx/brevitas/blob/513ab4dac112d16abfd17e7c8952e4c46ff14368/src/brevitas/export/common/handler/qcdq.py#L171

Bitwidth is in the wrong place

**Comment by OscarSavolainenDR** [comment]
Is this issue still open?  `QCDQDecoupledWeightQuantProxyHandlerMixin` seems to have been entirely removed from the coeebase.

**Comment by Giuseppe5** [comment]
We just made its name [longer](https://github.com/Xilinx/brevitas/blob/0570e8831814963f7999c2472db7c3328a6dcaa7/src/brevitas/export/common/handler/qcdq.py#L233C7-L233C52) :)
