### ISSUE TITLE
cannot import name 'activation_equalization_mode' from 'brevitas.graph.equalize'

### ISSUE THREAD

**Issue by Ba1tu3han** [Xilinx/brevitas#750]
Hello, 

I run below command and encountered this issue. What should I do? 

ba@ba:~/Xilinx/brevitas-dev/src/brevitas_examples/imagenet_classification/ptq$     python3 ptq_evaluate.py --calibration-dir ./calibration/ --validation-dir ./validation/ --gpu 0 --model-name mobilenetv1 --act-bit-width 8 --weight-bit-width 8 

Traceback (most recent call last):
  File "/home/ba/Xilinx/brevitas-dev/src/brevitas_examples/imagenet_classification/ptq/ptq_evaluate.py", line 20, in <module>
    from brevitas.graph.equalize import activation_equalization_mode
ImportError: cannot import name 'activation_equalization_mode' from 'brevitas.graph.equalize' (/home/ba/.local/lib/python3.10/site-packages/brevitas/graph/equalize.py)
ba@ba:~/Xilinx/brevitas-dev/src/brevitas_examples/imagenet_classification/ptq$ 

Best Regards, 
Batuhan

![image](https://github.com/Xilinx/brevitas/assets/29502318/f31311ac-131c-4c99-92dc-fc8d8472ea05)

**Comment by Giuseppe5** [comment]
Hello,

Are you using the `dev` branch of brevitas?
How have you installed brevitas?

**Comment by Ba1tu3han** [comment]
> Hello,
> 
> Are you using the `dev` branch of brevitas? How have you installed brevitas?

Hello,

yes, I’m using the dev branch and it is up to date. I pulled the repo via command line

**Comment by Giuseppe5** [comment]
From the root folder of brevitas, did you install it using: `pip install .` or `pip install -e .`?

**Comment by Ba1tu3han** [comment]
Yes, I have installed Brevitas also by using `pip install` command.

**Comment by fabianandresgrob** [comment]
Try using `pip install -e .` in the root folder of brevitas. @Ba1tu3han

**Comment by Ba1tu3han** [comment]
Thank you! it works.
