### ISSUE TITLE
SymbolicValueError During 4-bit Quantized CNN ONNX Export with Brevitas

### ISSUE THREAD

**Issue by Ba1tu3han** [Xilinx/brevitas#786]
## Prerequisites
Please make sure to check off these prerequisites before submitting a bug report.
- [x] Test that the bug appears on the current version of the dev-branch. Make sure to include the commit hash of the commit you checked out.
- [x] Check that the issue hasn't already been reported, by checking the currently open issues.
- [x] If there are steps to reproduce the problem, make sure to write them down below.
- [x] If relevant, please include the ONNX files, which were created directly before and/or after the bug.

## Quick summary
Encountering a SymbolicValueError during the export of a 4-bit quantized CNN model for MNIST dataset to ONNX format using Brevitas.

### Steps to Reproduce
    Setup environment with the latest dev version of Brevitas.
    Use the provided script for training a 4-bit quantized CNN on the MNIST dataset.
    Attempt to export the trained model to ONNX format using export_qonnx function from Brevitas.
    The script and the model architecture are as follows: [provide a brief description or a link to the script/model architecture].
    The resulting ONNX file and the error log are attached.

### Expected behavior
The model should be exported to ONNX format without any errors, allowing for further use in deployment scenarios.

### Actual behavior
The export process fails with a SymbolicValueError, indicating an issue with shape inference for onnx.brevitas::Quant type in the exported graph.

Python code: 
[brevitas-export-4wab-QONNX.zip](https://github.com/Xilinx/finn/files/13695918/brevitas-export-4wab-QONNX.zip)

![image](https://github.com/Xilinx/finn/assets/29502318/a0d37fc3-d3dc-4191-b2c2-096e85587c3b)
![image](https://github.com/Xilinx/finn/assets/29502318/c953e22e-6a66-4384-9e6e-7cd0cd4e11ab)

**Comment by Giuseppe5** [comment]
Hello,

I have tried your script and everything works fine with the latest release of Brevitas (0.10).

What PyTorch/Brevitas versions are you using?

**Comment by Ba1tu3han** [comment]
Hello,

I am using 0.9.1 Okay I will update it, thank you.

**Comment by Giuseppe5** [comment]
Happy to help!

Closing this, if the problem continues feel free to reopen.
