### ISSUE TITLE
Recurrent layers

### ISSUE THREAD

**Issue by volcacius** [Xilinx/brevitas#79]
This is an issue to track discussions around quantized RNN/GRU/LSTM implementation.

**Comment by Giuseppe5** [comment]
Compared to current implementations, it is required a small refactor of how computation is performed. 
After performing the quantization per gate, it looks like it's better to first concatenate weights to create two matrices (W_ih and W_hh), and after that perform the computation.
The JIT is able to fuse the kernel in a more efficient way and reduce the computation time.

**Comment by Giuseppe5** [comment]
Also, it is not clear for now if the requirement for pytorch >= 1.2.0 is still valid or can be removed, since we are using the old API for ScriptModule (torch.jit.ScriptModule instead of torch.jit.script(torch.nn.Module))

**Comment by volcacius** [comment]
There is some work to do to update this to new DI APIs

**Comment by Giuseppe5** [comment]
Outaded, closing
