### ISSUE TITLE
Questions about model storage

### ISSUE THREAD

**Issue by zxb-caffe** [Xilinx/brevitas#8]
Hello:
       How to save the model after quantification?
       Using    torch.save(model, 'model.pth')    will report an error, how can I solve it?

**Comment by volcacius** [comment]
You should load/save the model dict rather than trying to pickle the whole thing.
Save: torch.save(modelA.state_dict(), PATH)
Load: model.load_state_dict(torch.load(PATH))

Source:
https://pytorch.org/tutorials/beginner/saving_loading_models.html

**Comment by zxb-caffe** [comment]
thank you very much
