### ISSUE TITLE
Migration of FINN-Brevitas tests into Brevitas

### ISSUE THREAD

**Issue by volcacius** [Xilinx/brevitas#84]
This is an issue to track discussion around migrating Brevitas based tests in FINN into Brevitas. It should be on Brevitas to check that nothing breaks during the FINN export flow. Additionally, end to end inference tests on LFC and CNV should be moved together with the rest of end to end tests (#83).
The main issue is around how to setup FINN test enviroment within Github Actions.

Tagging: @maltanar

**Comment by maltanar** [comment]
We currently have a few tests hosted on the FINN compiler repo that we use to check the export:

https://github.com/Xilinx/finn/tree/dev/tests/brevitas

Currently FINN has a few big dependencies (like requiring a Vivado install) which makes it impractical to run tests in a cloud/SaaS environment. So we have a local Jenkins instance set up with all the dependencies etc. that gets triggered on new commits to the FINN dev branch that we use for testing at the moment. I see two options:

1) Host the Brevitas ONNX export / FINN import tests in our local Jenkins environment, triggering the particular set of tests when Brevitas gets new commits, then returning the results to GitHub actions interface somehow. (I'm not familiar with the GitHub actions interface, not sure if this is possible)
2) Provide a lightweight FINN Docker instance that is only used for testing the bare minimum necessary for Brevitas export, and run this on the cloud

Also, regarding testing for LFC and CNV, can you clarify what end-to-end means in this context? Do you mean end-to-end within Brevitas, or including all the steps that FINN goes through for hardware generation and bitfile synthesis? If the latter, then option 2 above would not really be feasible as the full FINN end2end flow will require Vivado.

**Comment by volcacius** [comment]
I'd rather go with option (2) given that conceptually (correct me if I'm wrong please) the subset of tests that I'd like to run don't depend on HLS or Vivado. I'm happy to take on the burden of trying to setup a minimal env and report back whatever might break.
Regarding testing of LFC and CNV, I mean end-to-end within Brevitas, so just inference on the pretrained models w.r.t. to known data. My goal would be to have the models (together with their training scripts) be part of the brevitas_examples package (see #76), and as such be directly importable wherever they are needed.

**Comment by volcacius** [comment]
Opened a pull request on FINN to deal with the fact that PyVerilator doesn't work on Windows: xilinx/finn#67.

**Comment by maltanar** [comment]
Sounds like a plan. The test_brevitas* tests should not need any Vivado HLS -- just the basic brevitas dependencies, and a few things from the FINN runtime (in turn depending on onnx, onnxruntime and the Python implementations for the FINN custom ops). There may also be minor issues about where temporary ONNX files get created during the export.

**Comment by volcacius** [comment]
Relevant issue in FINN for tests current failing on random W1A1 fc topologies: https://github.com/Xilinx/finn/issues/68 .

**Comment by volcacius** [comment]
Done.
