### ISSUE TITLE
Make notebook examples deterministic

### ISSUE THREAD

**Issue by nickfraser** [Xilinx/brevitas#842]
Some cells have a seed set, but we need to do this everywhere where it's necessary. This would make it much easier to verify them with a script.

**Comment by fabianandresgrob** [comment]
As `torch.manual_seed()` is creating a generator, it should be sufficient to set it once at the start of each notebook.
Or does a seed per cell (given that any numbers are generated) have any other advantages?

**Comment by nickfraser** [comment]
Start of the notebook should be fine, but we shouldn't change the cells where it is set explicitly.
