### ISSUE TITLE
Speech to text: Create en empty json file

### ISSUE THREAD

**Issue by rohanjuneja** [Xilinx/brevitas#864]
The command to download and preprocess the LibriSpeech dataset creates an empty json file.
brevitas_quartznet_preprocess --data_root=/path/to/validation/folder --data_set=DEV_OTHER

This causes the evaluation command to fail.

**Comment by Giuseppe5** [comment]
Thanks for pointing this out.
We will investigate the issue.

**Comment by Giuseppe5** [comment]
This should be fixed now. Thanks for opening the issue!
