### ISSUE TITLE
ONNX export of integer weights with large models

### ISSUE THREAD

**Issue by Giuseppe5** [Xilinx/brevitas#872]
When trying to export large models, currently we are forced to export QDQ pattern for weights, instead of simply exporting Integer weights -> DQ.

The error seems to be caused by the fact that adding a new node in the graph with integer weights confuses the calculation of the model size during torch export, and then the >2GB error is triggered.

To reproduce, using the [optimum-amd flow](https://github.com/huggingface/optimum-amd/tree/main/examples/quantization/brevitas):

```bash
CUDA_VISIBLE_DEVICES=0 python quantize_llm.py --model mistralai/Mistral-7B-v0.1
```
 with onnx==1.15.0, torch==2.2.0, brevitas==0.10.2, optimum==1.17.1, optimum-amd from main

Thanks @fxmarty

**Comment by fxmarty** [comment]
@costigt-dev @Giuseppe5 Brevitas seem to be using `Constant` for the int8 weights in ONNX, while PyTorch ONNX export / ORT quantizer use `Inititializer`. I'm not sure if this difference has any importance but just noting.

Can also be reproduced with `daryl149/llama-2-7b-chat-hf` & `transformers==4.38.1`

**Comment by Giuseppe5** [comment]
Maybe this could be relevant:
https://github.com/onnx/onnx/issues/5949

**Comment by costigt-dev** [comment]
From my investigations there doesn't appear to be any straightforward way to work around this issue in PyTorch 2.1 or below.
