### ISSUE TITLE
Question about quantification

### ISSUE THREAD

**Issue by zxb-caffe** [Xilinx/brevitas#9]
Hello:
      Please ask you the following questions:
      I quantified a network and got the file (.pth).
Question 1:
      The weights saved in this file are still float, not INT. When I access the property (QuantConv2d.int_weight), I can extract the integer representation of the weight. When inference, the first step is to convert the weight data type (float to INT). Can I understand this?
Question 2:
      Can you tell us about your quantification principle?

**Comment by volcacius** [comment]
1. Moving from a trained quantized network to actual integer execution is a problem of its own that is not covered by this library. As you noticed, you are free to extract the integer version of the weights and use them as part of your deployment flow.
2. Brevitas at the moment performs uniform symmetrical quantization with floating point or power-of-two scale factors (the latter translates to fixed point numbers). This sort of information will be detailed in the documentation in the future.

**Comment by zxb-caffe** [comment]
When inferring, is the type of weight INT?

**Comment by volcacius** [comment]
No. Even at inference time in brevitas the type of weights, inputs and outputs is floating point. Is up to you to extract the corresponding int compute graph from each layer.
