### ISSUE TITLE
update dependencies=2.0.1 requirement

### ISSUE THREAD

**Issue by isuruf** [Xilinx/brevitas#954]
I'm trying to package `brevitas` on conda-forge and the requirement `dependencies==2.0.1` is an issue as it's old. Is it possible to update this requirement to `7.7.0`?

**Comment by Giuseppe5** [comment]
Thanks for pointing this out.

Brevitas is not compatible with more recent version of `dependencies` unfortunately.

What error do you get?

**Comment by isuruf** [comment]
conda says that `depdendencies==2.0.1` is not found. Here are the versions that are available: https://anaconda.org/conda-forge/dependencies/files

**Comment by Giuseppe5** [comment]
Use pip, that should solve that:
https://pypi.org/project/dependencies/#history
